package com.tti.accscms.dao.clientmanagement;

import java.util.List;

import com.tti.accscms.domain.clientmanagement.RequestLog;
import com.tti.accscms.domain.clientmanagement.RequestLogExample;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table request_log
 */
public interface RequestLogDao {
    
    public long count() throws DaoException;

    public int deleteById(Long id) throws DaoException;

    public long insert(RequestLog requestLog) throws DaoException;

    public RequestLog findById(Long id) throws DaoException;
	
	public int update(RequestLog requestLog) throws DaoException;
	
	public long countByRequestLogExample(RequestLogExample requestLogExample) throws DaoException;
	
	public RequestLog findByRequestLogExample(RequestLogExample requestLogExample) throws DaoException;
	
    public List<RequestLog> findAllByRequestLogExample(RequestLogExample requestLogExample) throws DaoException;
    
    public List<RequestLog> findAllByRequestLogExample(RequestLogExample requestLogExample, int limit) throws DaoException;
    
    public List<RequestLog> findAllByRequestLogExample(RequestLogExample requestLogExample, int offset, int limit) throws DaoException;
}
