package com.tti.accscms.domain.movement;

import java.util.Date;

public class ChangeAirportLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column change_airport_log.id
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column change_airport_log.id2
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	private Integer id2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column change_airport_log.change_airport_id
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	private Integer changeAirportId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column change_airport_log.user
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	private String user;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column change_airport_log.desc
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column change_airport_log.date_time
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	private Date dateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column change_airport_log.id
	 * @return  the value of change_airport_log.id
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column change_airport_log.id
	 * @param id  the value for change_airport_log.id
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column change_airport_log.id2
	 * @return  the value of change_airport_log.id2
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public Integer getId2() {
		return id2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column change_airport_log.id2
	 * @param id2  the value for change_airport_log.id2
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public void setId2(Integer id2) {
		this.id2 = id2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column change_airport_log.change_airport_id
	 * @return  the value of change_airport_log.change_airport_id
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public Integer getChangeAirportId() {
		return changeAirportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column change_airport_log.change_airport_id
	 * @param changeAirportId  the value for change_airport_log.change_airport_id
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public void setChangeAirportId(Integer changeAirportId) {
		this.changeAirportId = changeAirportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column change_airport_log.user
	 * @return  the value of change_airport_log.user
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column change_airport_log.user
	 * @param user  the value for change_airport_log.user
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column change_airport_log.desc
	 * @return  the value of change_airport_log.desc
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column change_airport_log.desc
	 * @param desc  the value for change_airport_log.desc
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column change_airport_log.date_time
	 * @return  the value of change_airport_log.date_time
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public Date getDateTime() {
		return dateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column change_airport_log.date_time
	 * @param dateTime  the value for change_airport_log.date_time
	 * @mbggenerated  Wed Dec 26 12:07:01 ICT 2012
	 */
	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}
}