package com.tti.accscms.domain.movement;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExpressCustomsPermitDetailHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public ExpressCustomsPermitDetailHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andId2IsNull() {
            addCriterion("id2 is null");
            return (Criteria) this;
        }

        public Criteria andId2IsNotNull() {
            addCriterion("id2 is not null");
            return (Criteria) this;
        }

        public Criteria andId2EqualTo(Integer value) {
            addCriterion("id2 =", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotEqualTo(Integer value) {
            addCriterion("id2 <>", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2GreaterThan(Integer value) {
            addCriterion("id2 >", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2GreaterThanOrEqualTo(Integer value) {
            addCriterion("id2 >=", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2LessThan(Integer value) {
            addCriterion("id2 <", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2LessThanOrEqualTo(Integer value) {
            addCriterion("id2 <=", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2In(List<Integer> values) {
            addCriterion("id2 in", values, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotIn(List<Integer> values) {
            addCriterion("id2 not in", values, "id2");
            return (Criteria) this;
        }

        public Criteria andId2Between(Integer value1, Integer value2) {
            addCriterion("id2 between", value1, value2, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotBetween(Integer value1, Integer value2) {
            addCriterion("id2 not between", value1, value2, "id2");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdIsNull() {
            addCriterion("exp_customs_permit_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdIsNotNull() {
            addCriterion("exp_customs_permit_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdEqualTo(Integer value) {
            addCriterion("exp_customs_permit_detail_id =", value, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdNotEqualTo(Integer value) {
            addCriterion("exp_customs_permit_detail_id <>", value, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdGreaterThan(Integer value) {
            addCriterion("exp_customs_permit_detail_id >", value, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exp_customs_permit_detail_id >=", value, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdLessThan(Integer value) {
            addCriterion("exp_customs_permit_detail_id <", value, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("exp_customs_permit_detail_id <=", value, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdIn(List<Integer> values) {
            addCriterion("exp_customs_permit_detail_id in", values, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdNotIn(List<Integer> values) {
            addCriterion("exp_customs_permit_detail_id not in", values, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("exp_customs_permit_detail_id between", value1, value2, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andExpCustomsPermitDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exp_customs_permit_detail_id not between", value1, value2, "expCustomsPermitDetailId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdIsNull() {
            addCriterion("permit_header_id is null");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdIsNotNull() {
            addCriterion("permit_header_id is not null");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdEqualTo(Integer value) {
            addCriterion("permit_header_id =", value, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdNotEqualTo(Integer value) {
            addCriterion("permit_header_id <>", value, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdGreaterThan(Integer value) {
            addCriterion("permit_header_id >", value, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("permit_header_id >=", value, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdLessThan(Integer value) {
            addCriterion("permit_header_id <", value, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdLessThanOrEqualTo(Integer value) {
            addCriterion("permit_header_id <=", value, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdIn(List<Integer> values) {
            addCriterion("permit_header_id in", values, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdNotIn(List<Integer> values) {
            addCriterion("permit_header_id not in", values, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdBetween(Integer value1, Integer value2) {
            addCriterion("permit_header_id between", value1, value2, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andPermitHeaderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("permit_header_id not between", value1, value2, "permitHeaderId");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoIsNull() {
            addCriterion("declaration_line_no is null");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoIsNotNull() {
            addCriterion("declaration_line_no is not null");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoEqualTo(Integer value) {
            addCriterion("declaration_line_no =", value, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoNotEqualTo(Integer value) {
            addCriterion("declaration_line_no <>", value, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoGreaterThan(Integer value) {
            addCriterion("declaration_line_no >", value, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("declaration_line_no >=", value, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoLessThan(Integer value) {
            addCriterion("declaration_line_no <", value, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoLessThanOrEqualTo(Integer value) {
            addCriterion("declaration_line_no <=", value, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoIn(List<Integer> values) {
            addCriterion("declaration_line_no in", values, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoNotIn(List<Integer> values) {
            addCriterion("declaration_line_no not in", values, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoBetween(Integer value1, Integer value2) {
            addCriterion("declaration_line_no between", value1, value2, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andDeclarationLineNoNotBetween(Integer value1, Integer value2) {
            addCriterion("declaration_line_no not between", value1, value2, "declarationLineNo");
            return (Criteria) this;
        }

        public Criteria andHawbIsNull() {
            addCriterion("hawb is null");
            return (Criteria) this;
        }

        public Criteria andHawbIsNotNull() {
            addCriterion("hawb is not null");
            return (Criteria) this;
        }

        public Criteria andHawbEqualTo(String value) {
            addCriterion("hawb =", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbNotEqualTo(String value) {
            addCriterion("hawb <>", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbGreaterThan(String value) {
            addCriterion("hawb >", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbGreaterThanOrEqualTo(String value) {
            addCriterion("hawb >=", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbLessThan(String value) {
            addCriterion("hawb <", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbLessThanOrEqualTo(String value) {
            addCriterion("hawb <=", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbLike(String value) {
            addCriterion("hawb like", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbNotLike(String value) {
            addCriterion("hawb not like", value, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbIn(List<String> values) {
            addCriterion("hawb in", values, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbNotIn(List<String> values) {
            addCriterion("hawb not in", values, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbBetween(String value1, String value2) {
            addCriterion("hawb between", value1, value2, "hawb");
            return (Criteria) this;
        }

        public Criteria andHawbNotBetween(String value1, String value2) {
            addCriterion("hawb not between", value1, value2, "hawb");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeIsNull() {
            addCriterion("modified_date_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeIsNotNull() {
            addCriterion("modified_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeEqualTo(Date value) {
            addCriterion("modified_date_time =", value, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeNotEqualTo(Date value) {
            addCriterion("modified_date_time <>", value, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeGreaterThan(Date value) {
            addCriterion("modified_date_time >", value, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_date_time >=", value, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeLessThan(Date value) {
            addCriterion("modified_date_time <", value, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_date_time <=", value, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeIn(List<Date> values) {
            addCriterion("modified_date_time in", values, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeNotIn(List<Date> values) {
            addCriterion("modified_date_time not in", values, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeBetween(Date value1, Date value2) {
            addCriterion("modified_date_time between", value1, value2, "modifiedDateTime");
            return (Criteria) this;
        }

        public Criteria andModifiedDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_date_time not between", value1, value2, "modifiedDateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 26 12:07:01 ICT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exp_customs_permit_detail_his
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}