package com.tti.accscms.domain.movement;

import java.util.Date;

public class Faulty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.id2
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.declaration_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String declarationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.faulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date faultyDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.user_faulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String userFaulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.user_unfaulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String userUnfaulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.company_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.company_code
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.shed_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String shedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.tmo_remark
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String tmoRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.tmo_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer tmoNumberOfPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.tmo_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Double tmoGrossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.customs_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer customsNumberOfPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.customs_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Double customsGrossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.customs_user
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String customsUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.customs_remark
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String customsRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.customs_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String customsNumberOfPackageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.customs_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String customsGrossWeightUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.tmo_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String tmoNumberOfPackageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.tmo_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String tmoGrossWeightUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date modifiedDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.unfaulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date unfaultyDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String mawb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String hawb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String flightNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faulty.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date flightDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.id
     *
     * @return the value of faulty.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.id
     *
     * @param id the value for faulty.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.id2
     *
     * @return the value of faulty.id2
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.id2
     *
     * @param id2 the value for faulty.id2
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setId2(Integer id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.declaration_no
     *
     * @return the value of faulty.declaration_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getDeclarationNo() {
        return declarationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.declaration_no
     *
     * @param declarationNo the value for faulty.declaration_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setDeclarationNo(String declarationNo) {
        this.declarationNo = declarationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.faulty_date_time
     *
     * @return the value of faulty.faulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getFaultyDateTime() {
        return faultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.faulty_date_time
     *
     * @param faultyDateTime the value for faulty.faulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFaultyDateTime(Date faultyDateTime) {
        this.faultyDateTime = faultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.user_faulty
     *
     * @return the value of faulty.user_faulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getUserFaulty() {
        return userFaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.user_faulty
     *
     * @param userFaulty the value for faulty.user_faulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setUserFaulty(String userFaulty) {
        this.userFaulty = userFaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.user_unfaulty
     *
     * @return the value of faulty.user_unfaulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getUserUnfaulty() {
        return userUnfaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.user_unfaulty
     *
     * @param userUnfaulty the value for faulty.user_unfaulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setUserUnfaulty(String userUnfaulty) {
        this.userUnfaulty = userUnfaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.status
     *
     * @return the value of faulty.status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.status
     *
     * @param status the value for faulty.status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.company_type
     *
     * @return the value of faulty.company_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.company_type
     *
     * @param companyType the value for faulty.company_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.company_code
     *
     * @return the value of faulty.company_code
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.company_code
     *
     * @param companyCode the value for faulty.company_code
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.shed_no
     *
     * @return the value of faulty.shed_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getShedNo() {
        return shedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.shed_no
     *
     * @param shedNo the value for faulty.shed_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setShedNo(String shedNo) {
        this.shedNo = shedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.tmo_remark
     *
     * @return the value of faulty.tmo_remark
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getTmoRemark() {
        return tmoRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.tmo_remark
     *
     * @param tmoRemark the value for faulty.tmo_remark
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setTmoRemark(String tmoRemark) {
        this.tmoRemark = tmoRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.tmo_number_of_package
     *
     * @return the value of faulty.tmo_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getTmoNumberOfPackage() {
        return tmoNumberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.tmo_number_of_package
     *
     * @param tmoNumberOfPackage the value for faulty.tmo_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setTmoNumberOfPackage(Integer tmoNumberOfPackage) {
        this.tmoNumberOfPackage = tmoNumberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.tmo_gross_weight
     *
     * @return the value of faulty.tmo_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Double getTmoGrossWeight() {
        return tmoGrossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.tmo_gross_weight
     *
     * @param tmoGrossWeight the value for faulty.tmo_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setTmoGrossWeight(Double tmoGrossWeight) {
        this.tmoGrossWeight = tmoGrossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.customs_number_of_package
     *
     * @return the value of faulty.customs_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getCustomsNumberOfPackage() {
        return customsNumberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.customs_number_of_package
     *
     * @param customsNumberOfPackage the value for faulty.customs_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCustomsNumberOfPackage(Integer customsNumberOfPackage) {
        this.customsNumberOfPackage = customsNumberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.customs_gross_weight
     *
     * @return the value of faulty.customs_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Double getCustomsGrossWeight() {
        return customsGrossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.customs_gross_weight
     *
     * @param customsGrossWeight the value for faulty.customs_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCustomsGrossWeight(Double customsGrossWeight) {
        this.customsGrossWeight = customsGrossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.customs_user
     *
     * @return the value of faulty.customs_user
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCustomsUser() {
        return customsUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.customs_user
     *
     * @param customsUser the value for faulty.customs_user
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCustomsUser(String customsUser) {
        this.customsUser = customsUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.customs_remark
     *
     * @return the value of faulty.customs_remark
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCustomsRemark() {
        return customsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.customs_remark
     *
     * @param customsRemark the value for faulty.customs_remark
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCustomsRemark(String customsRemark) {
        this.customsRemark = customsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.customs_number_of_package_unit
     *
     * @return the value of faulty.customs_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCustomsNumberOfPackageUnit() {
        return customsNumberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.customs_number_of_package_unit
     *
     * @param customsNumberOfPackageUnit the value for faulty.customs_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCustomsNumberOfPackageUnit(String customsNumberOfPackageUnit) {
        this.customsNumberOfPackageUnit = customsNumberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.customs_gross_weight_unit
     *
     * @return the value of faulty.customs_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCustomsGrossWeightUnit() {
        return customsGrossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.customs_gross_weight_unit
     *
     * @param customsGrossWeightUnit the value for faulty.customs_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCustomsGrossWeightUnit(String customsGrossWeightUnit) {
        this.customsGrossWeightUnit = customsGrossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.tmo_number_of_package_unit
     *
     * @return the value of faulty.tmo_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getTmoNumberOfPackageUnit() {
        return tmoNumberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.tmo_number_of_package_unit
     *
     * @param tmoNumberOfPackageUnit the value for faulty.tmo_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setTmoNumberOfPackageUnit(String tmoNumberOfPackageUnit) {
        this.tmoNumberOfPackageUnit = tmoNumberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.tmo_gross_weight_unit
     *
     * @return the value of faulty.tmo_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getTmoGrossWeightUnit() {
        return tmoGrossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.tmo_gross_weight_unit
     *
     * @param tmoGrossWeightUnit the value for faulty.tmo_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setTmoGrossWeightUnit(String tmoGrossWeightUnit) {
        this.tmoGrossWeightUnit = tmoGrossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.modified_date_time
     *
     * @return the value of faulty.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getModifiedDateTime() {
        return modifiedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.modified_date_time
     *
     * @param modifiedDateTime the value for faulty.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setModifiedDateTime(Date modifiedDateTime) {
        this.modifiedDateTime = modifiedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.unfaulty_date_time
     *
     * @return the value of faulty.unfaulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getUnfaultyDateTime() {
        return unfaultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.unfaulty_date_time
     *
     * @param unfaultyDateTime the value for faulty.unfaulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setUnfaultyDateTime(Date unfaultyDateTime) {
        this.unfaultyDateTime = unfaultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.mawb
     *
     * @return the value of faulty.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getMawb() {
        return mawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.mawb
     *
     * @param mawb the value for faulty.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setMawb(String mawb) {
        this.mawb = mawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.hawb
     *
     * @return the value of faulty.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getHawb() {
        return hawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.hawb
     *
     * @param hawb the value for faulty.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setHawb(String hawb) {
        this.hawb = hawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.flight_no
     *
     * @return the value of faulty.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getFlightNo() {
        return flightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.flight_no
     *
     * @param flightNo the value for faulty.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faulty.flight_date
     *
     * @return the value of faulty.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getFlightDate() {
        return flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faulty.flight_date
     *
     * @param flightDate the value for faulty.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }
}