package com.tti.accscms.domain.movement;

import java.util.Date;

public class GoodsTransition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.id2
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.declaration_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String declarationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.company_tax_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String companyTaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.company_branch
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer companyBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer numberOfPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String numberOfPackageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Double grossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String grossWeightUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.last_entry
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String lastEntry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date modifiedDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String mawb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String hawb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.goods_description
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String goodsDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.status_0309
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String status0309;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.status_0309_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date status0309DateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.status_0309_by
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String status0309By;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.remark_0309
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String remark0309;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.balanced
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer balanced;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.balanced_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date balancedDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.balanced_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String balancedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.shipper_name
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String shipperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.remain_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer remainNumberOfPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.remain_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String remainNumberOfPackageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.remain_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Double remainGrossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.remain_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String remainGrossWeightUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.reference_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String referenceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.company_name
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.street_and_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String streetAndNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.postcode
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.car_license
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String carLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.container_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String containerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.container_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer containerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.container_code
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String containerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String flightNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date flightDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.release_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer releasePort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.load_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer loadPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.packing_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer packingPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.discharge_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String dischargePort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.e_seal
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String eSeal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.detail_line
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer detailLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.is_edit_manual
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer isEditManual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.is_manual
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer isManual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.group_declaration
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer groupDeclaration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.is_from_customs
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer isFromCustoms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_transition.receive_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date receiveDateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.id
     *
     * @return the value of goods_transition.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.id
     *
     * @param id the value for goods_transition.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.id2
     *
     * @return the value of goods_transition.id2
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.id2
     *
     * @param id2 the value for goods_transition.id2
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setId2(Integer id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.declaration_no
     *
     * @return the value of goods_transition.declaration_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getDeclarationNo() {
        return declarationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.declaration_no
     *
     * @param declarationNo the value for goods_transition.declaration_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setDeclarationNo(String declarationNo) {
        this.declarationNo = declarationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.company_tax_no
     *
     * @return the value of goods_transition.company_tax_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCompanyTaxNo() {
        return companyTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.company_tax_no
     *
     * @param companyTaxNo the value for goods_transition.company_tax_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCompanyTaxNo(String companyTaxNo) {
        this.companyTaxNo = companyTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.company_branch
     *
     * @return the value of goods_transition.company_branch
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getCompanyBranch() {
        return companyBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.company_branch
     *
     * @param companyBranch the value for goods_transition.company_branch
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCompanyBranch(Integer companyBranch) {
        this.companyBranch = companyBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.number_of_package
     *
     * @return the value of goods_transition.number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getNumberOfPackage() {
        return numberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.number_of_package
     *
     * @param numberOfPackage the value for goods_transition.number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setNumberOfPackage(Integer numberOfPackage) {
        this.numberOfPackage = numberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.number_of_package_unit
     *
     * @return the value of goods_transition.number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getNumberOfPackageUnit() {
        return numberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.number_of_package_unit
     *
     * @param numberOfPackageUnit the value for goods_transition.number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setNumberOfPackageUnit(String numberOfPackageUnit) {
        this.numberOfPackageUnit = numberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.gross_weight
     *
     * @return the value of goods_transition.gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Double getGrossWeight() {
        return grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.gross_weight
     *
     * @param grossWeight the value for goods_transition.gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setGrossWeight(Double grossWeight) {
        this.grossWeight = grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.gross_weight_unit
     *
     * @return the value of goods_transition.gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getGrossWeightUnit() {
        return grossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.gross_weight_unit
     *
     * @param grossWeightUnit the value for goods_transition.gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setGrossWeightUnit(String grossWeightUnit) {
        this.grossWeightUnit = grossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.last_entry
     *
     * @return the value of goods_transition.last_entry
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getLastEntry() {
        return lastEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.last_entry
     *
     * @param lastEntry the value for goods_transition.last_entry
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setLastEntry(String lastEntry) {
        this.lastEntry = lastEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.modified_date_time
     *
     * @return the value of goods_transition.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getModifiedDateTime() {
        return modifiedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.modified_date_time
     *
     * @param modifiedDateTime the value for goods_transition.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setModifiedDateTime(Date modifiedDateTime) {
        this.modifiedDateTime = modifiedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.mawb
     *
     * @return the value of goods_transition.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getMawb() {
        return mawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.mawb
     *
     * @param mawb the value for goods_transition.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setMawb(String mawb) {
        this.mawb = mawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.hawb
     *
     * @return the value of goods_transition.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getHawb() {
        return hawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.hawb
     *
     * @param hawb the value for goods_transition.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setHawb(String hawb) {
        this.hawb = hawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.goods_description
     *
     * @return the value of goods_transition.goods_description
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getGoodsDescription() {
        return goodsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.goods_description
     *
     * @param goodsDescription the value for goods_transition.goods_description
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setGoodsDescription(String goodsDescription) {
        this.goodsDescription = goodsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.status_0309
     *
     * @return the value of goods_transition.status_0309
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getStatus0309() {
        return status0309;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.status_0309
     *
     * @param status0309 the value for goods_transition.status_0309
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setStatus0309(String status0309) {
        this.status0309 = status0309;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.status_0309_date_time
     *
     * @return the value of goods_transition.status_0309_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getStatus0309DateTime() {
        return status0309DateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.status_0309_date_time
     *
     * @param status0309DateTime the value for goods_transition.status_0309_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setStatus0309DateTime(Date status0309DateTime) {
        this.status0309DateTime = status0309DateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.status_0309_by
     *
     * @return the value of goods_transition.status_0309_by
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getStatus0309By() {
        return status0309By;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.status_0309_by
     *
     * @param status0309By the value for goods_transition.status_0309_by
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setStatus0309By(String status0309By) {
        this.status0309By = status0309By;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.remark_0309
     *
     * @return the value of goods_transition.remark_0309
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getRemark0309() {
        return remark0309;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.remark_0309
     *
     * @param remark0309 the value for goods_transition.remark_0309
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setRemark0309(String remark0309) {
        this.remark0309 = remark0309;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.balanced
     *
     * @return the value of goods_transition.balanced
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getBalanced() {
        return balanced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.balanced
     *
     * @param balanced the value for goods_transition.balanced
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setBalanced(Integer balanced) {
        this.balanced = balanced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.balanced_date_time
     *
     * @return the value of goods_transition.balanced_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getBalancedDateTime() {
        return balancedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.balanced_date_time
     *
     * @param balancedDateTime the value for goods_transition.balanced_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setBalancedDateTime(Date balancedDateTime) {
        this.balancedDateTime = balancedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.balanced_type
     *
     * @return the value of goods_transition.balanced_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getBalancedType() {
        return balancedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.balanced_type
     *
     * @param balancedType the value for goods_transition.balanced_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setBalancedType(String balancedType) {
        this.balancedType = balancedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.shipper_name
     *
     * @return the value of goods_transition.shipper_name
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getShipperName() {
        return shipperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.shipper_name
     *
     * @param shipperName the value for goods_transition.shipper_name
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setShipperName(String shipperName) {
        this.shipperName = shipperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.remain_number_of_package
     *
     * @return the value of goods_transition.remain_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getRemainNumberOfPackage() {
        return remainNumberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.remain_number_of_package
     *
     * @param remainNumberOfPackage the value for goods_transition.remain_number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setRemainNumberOfPackage(Integer remainNumberOfPackage) {
        this.remainNumberOfPackage = remainNumberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.remain_number_of_package_unit
     *
     * @return the value of goods_transition.remain_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getRemainNumberOfPackageUnit() {
        return remainNumberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.remain_number_of_package_unit
     *
     * @param remainNumberOfPackageUnit the value for goods_transition.remain_number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setRemainNumberOfPackageUnit(String remainNumberOfPackageUnit) {
        this.remainNumberOfPackageUnit = remainNumberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.remain_gross_weight
     *
     * @return the value of goods_transition.remain_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Double getRemainGrossWeight() {
        return remainGrossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.remain_gross_weight
     *
     * @param remainGrossWeight the value for goods_transition.remain_gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setRemainGrossWeight(Double remainGrossWeight) {
        this.remainGrossWeight = remainGrossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.remain_gross_weight_unit
     *
     * @return the value of goods_transition.remain_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getRemainGrossWeightUnit() {
        return remainGrossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.remain_gross_weight_unit
     *
     * @param remainGrossWeightUnit the value for goods_transition.remain_gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setRemainGrossWeightUnit(String remainGrossWeightUnit) {
        this.remainGrossWeightUnit = remainGrossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.reference_number
     *
     * @return the value of goods_transition.reference_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.reference_number
     *
     * @param referenceNumber the value for goods_transition.reference_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.company_name
     *
     * @return the value of goods_transition.company_name
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.company_name
     *
     * @param companyName the value for goods_transition.company_name
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.street_and_number
     *
     * @return the value of goods_transition.street_and_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getStreetAndNumber() {
        return streetAndNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.street_and_number
     *
     * @param streetAndNumber the value for goods_transition.street_and_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setStreetAndNumber(String streetAndNumber) {
        this.streetAndNumber = streetAndNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.postcode
     *
     * @return the value of goods_transition.postcode
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.postcode
     *
     * @param postcode the value for goods_transition.postcode
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.car_license
     *
     * @return the value of goods_transition.car_license
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getCarLicense() {
        return carLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.car_license
     *
     * @param carLicense the value for goods_transition.car_license
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setCarLicense(String carLicense) {
        this.carLicense = carLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.container_number
     *
     * @return the value of goods_transition.container_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getContainerNumber() {
        return containerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.container_number
     *
     * @param containerNumber the value for goods_transition.container_number
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setContainerNumber(String containerNumber) {
        this.containerNumber = containerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.container_type
     *
     * @return the value of goods_transition.container_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getContainerType() {
        return containerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.container_type
     *
     * @param containerType the value for goods_transition.container_type
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setContainerType(Integer containerType) {
        this.containerType = containerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.container_code
     *
     * @return the value of goods_transition.container_code
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getContainerCode() {
        return containerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.container_code
     *
     * @param containerCode the value for goods_transition.container_code
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setContainerCode(String containerCode) {
        this.containerCode = containerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.flight_no
     *
     * @return the value of goods_transition.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getFlightNo() {
        return flightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.flight_no
     *
     * @param flightNo the value for goods_transition.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.flight_date
     *
     * @return the value of goods_transition.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getFlightDate() {
        return flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.flight_date
     *
     * @param flightDate the value for goods_transition.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.release_port
     *
     * @return the value of goods_transition.release_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getReleasePort() {
        return releasePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.release_port
     *
     * @param releasePort the value for goods_transition.release_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setReleasePort(Integer releasePort) {
        this.releasePort = releasePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.load_port
     *
     * @return the value of goods_transition.load_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getLoadPort() {
        return loadPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.load_port
     *
     * @param loadPort the value for goods_transition.load_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setLoadPort(Integer loadPort) {
        this.loadPort = loadPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.packing_port
     *
     * @return the value of goods_transition.packing_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getPackingPort() {
        return packingPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.packing_port
     *
     * @param packingPort the value for goods_transition.packing_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setPackingPort(Integer packingPort) {
        this.packingPort = packingPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.discharge_port
     *
     * @return the value of goods_transition.discharge_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getDischargePort() {
        return dischargePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.discharge_port
     *
     * @param dischargePort the value for goods_transition.discharge_port
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setDischargePort(String dischargePort) {
        this.dischargePort = dischargePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.e_seal
     *
     * @return the value of goods_transition.e_seal
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String geteSeal() {
        return eSeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.e_seal
     *
     * @param eSeal the value for goods_transition.e_seal
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void seteSeal(String eSeal) {
        this.eSeal = eSeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.detail_line
     *
     * @return the value of goods_transition.detail_line
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getDetailLine() {
        return detailLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.detail_line
     *
     * @param detailLine the value for goods_transition.detail_line
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setDetailLine(Integer detailLine) {
        this.detailLine = detailLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.is_edit_manual
     *
     * @return the value of goods_transition.is_edit_manual
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getIsEditManual() {
        return isEditManual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.is_edit_manual
     *
     * @param isEditManual the value for goods_transition.is_edit_manual
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setIsEditManual(Integer isEditManual) {
        this.isEditManual = isEditManual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.is_manual
     *
     * @return the value of goods_transition.is_manual
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getIsManual() {
        return isManual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.is_manual
     *
     * @param isManual the value for goods_transition.is_manual
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setIsManual(Integer isManual) {
        this.isManual = isManual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.group_declaration
     *
     * @return the value of goods_transition.group_declaration
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getGroupDeclaration() {
        return groupDeclaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.group_declaration
     *
     * @param groupDeclaration the value for goods_transition.group_declaration
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setGroupDeclaration(Integer groupDeclaration) {
        this.groupDeclaration = groupDeclaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.is_from_customs
     *
     * @return the value of goods_transition.is_from_customs
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getIsFromCustoms() {
        return isFromCustoms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.is_from_customs
     *
     * @param isFromCustoms the value for goods_transition.is_from_customs
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setIsFromCustoms(Integer isFromCustoms) {
        this.isFromCustoms = isFromCustoms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_transition.receive_date_time
     *
     * @return the value of goods_transition.receive_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getReceiveDateTime() {
        return receiveDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_transition.receive_date_time
     *
     * @param receiveDateTime the value for goods_transition.receive_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setReceiveDateTime(Date receiveDateTime) {
        this.receiveDateTime = receiveDateTime;
    }
}