package com.tti.accscms.domain.movement;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LogWSExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public LogWSExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andId2IsNull() {
            addCriterion("id2 is null");
            return (Criteria) this;
        }

        public Criteria andId2IsNotNull() {
            addCriterion("id2 is not null");
            return (Criteria) this;
        }

        public Criteria andId2EqualTo(Integer value) {
            addCriterion("id2 =", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotEqualTo(Integer value) {
            addCriterion("id2 <>", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2GreaterThan(Integer value) {
            addCriterion("id2 >", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2GreaterThanOrEqualTo(Integer value) {
            addCriterion("id2 >=", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2LessThan(Integer value) {
            addCriterion("id2 <", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2LessThanOrEqualTo(Integer value) {
            addCriterion("id2 <=", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2In(List<Integer> values) {
            addCriterion("id2 in", values, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotIn(List<Integer> values) {
            addCriterion("id2 not in", values, "id2");
            return (Criteria) this;
        }

        public Criteria andId2Between(Integer value1, Integer value2) {
            addCriterion("id2 between", value1, value2, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotBetween(Integer value1, Integer value2) {
            addCriterion("id2 not between", value1, value2, "id2");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdIsNull() {
            addCriterion("user_company_id is null");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdIsNotNull() {
            addCriterion("user_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdEqualTo(Integer value) {
            addCriterion("user_company_id =", value, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdNotEqualTo(Integer value) {
            addCriterion("user_company_id <>", value, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdGreaterThan(Integer value) {
            addCriterion("user_company_id >", value, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_company_id >=", value, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdLessThan(Integer value) {
            addCriterion("user_company_id <", value, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_company_id <=", value, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdIn(List<Integer> values) {
            addCriterion("user_company_id in", values, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdNotIn(List<Integer> values) {
            addCriterion("user_company_id not in", values, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("user_company_id between", value1, value2, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_company_id not between", value1, value2, "userCompanyId");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressIsNull() {
            addCriterion("client_ip_address is null");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressIsNotNull() {
            addCriterion("client_ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressEqualTo(String value) {
            addCriterion("client_ip_address =", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressNotEqualTo(String value) {
            addCriterion("client_ip_address <>", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressGreaterThan(String value) {
            addCriterion("client_ip_address >", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("client_ip_address >=", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressLessThan(String value) {
            addCriterion("client_ip_address <", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressLessThanOrEqualTo(String value) {
            addCriterion("client_ip_address <=", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressLike(String value) {
            addCriterion("client_ip_address like", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressNotLike(String value) {
            addCriterion("client_ip_address not like", value, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressIn(List<String> values) {
            addCriterion("client_ip_address in", values, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressNotIn(List<String> values) {
            addCriterion("client_ip_address not in", values, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressBetween(String value1, String value2) {
            addCriterion("client_ip_address between", value1, value2, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andClientIpAddressNotBetween(String value1, String value2) {
            addCriterion("client_ip_address not between", value1, value2, "clientIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressIsNull() {
            addCriterion("server_ip_address is null");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressIsNotNull() {
            addCriterion("server_ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressEqualTo(String value) {
            addCriterion("server_ip_address =", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressNotEqualTo(String value) {
            addCriterion("server_ip_address <>", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressGreaterThan(String value) {
            addCriterion("server_ip_address >", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("server_ip_address >=", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressLessThan(String value) {
            addCriterion("server_ip_address <", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressLessThanOrEqualTo(String value) {
            addCriterion("server_ip_address <=", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressLike(String value) {
            addCriterion("server_ip_address like", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressNotLike(String value) {
            addCriterion("server_ip_address not like", value, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressIn(List<String> values) {
            addCriterion("server_ip_address in", values, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressNotIn(List<String> values) {
            addCriterion("server_ip_address not in", values, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressBetween(String value1, String value2) {
            addCriterion("server_ip_address between", value1, value2, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServerIpAddressNotBetween(String value1, String value2) {
            addCriterion("server_ip_address not between", value1, value2, "serverIpAddress");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNull() {
            addCriterion("service_name is null");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNotNull() {
            addCriterion("service_name is not null");
            return (Criteria) this;
        }

        public Criteria andServiceNameEqualTo(String value) {
            addCriterion("service_name =", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotEqualTo(String value) {
            addCriterion("service_name <>", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThan(String value) {
            addCriterion("service_name >", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThanOrEqualTo(String value) {
            addCriterion("service_name >=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThan(String value) {
            addCriterion("service_name <", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThanOrEqualTo(String value) {
            addCriterion("service_name <=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLike(String value) {
            addCriterion("service_name like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotLike(String value) {
            addCriterion("service_name not like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameIn(List<String> values) {
            addCriterion("service_name in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotIn(List<String> values) {
            addCriterion("service_name not in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameBetween(String value1, String value2) {
            addCriterion("service_name between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotBetween(String value1, String value2) {
            addCriterion("service_name not between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andOperationNameIsNull() {
            addCriterion("operation_name is null");
            return (Criteria) this;
        }

        public Criteria andOperationNameIsNotNull() {
            addCriterion("operation_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperationNameEqualTo(String value) {
            addCriterion("operation_name =", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotEqualTo(String value) {
            addCriterion("operation_name <>", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameGreaterThan(String value) {
            addCriterion("operation_name >", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameGreaterThanOrEqualTo(String value) {
            addCriterion("operation_name >=", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameLessThan(String value) {
            addCriterion("operation_name <", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameLessThanOrEqualTo(String value) {
            addCriterion("operation_name <=", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameLike(String value) {
            addCriterion("operation_name like", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotLike(String value) {
            addCriterion("operation_name not like", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameIn(List<String> values) {
            addCriterion("operation_name in", values, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotIn(List<String> values) {
            addCriterion("operation_name not in", values, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameBetween(String value1, String value2) {
            addCriterion("operation_name between", value1, value2, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotBetween(String value1, String value2) {
            addCriterion("operation_name not between", value1, value2, "operationName");
            return (Criteria) this;
        }

        public Criteria andInboundIsNull() {
            addCriterion("inbound is null");
            return (Criteria) this;
        }

        public Criteria andInboundIsNotNull() {
            addCriterion("inbound is not null");
            return (Criteria) this;
        }

        public Criteria andInboundEqualTo(String value) {
            addCriterion("inbound =", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundNotEqualTo(String value) {
            addCriterion("inbound <>", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundGreaterThan(String value) {
            addCriterion("inbound >", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundGreaterThanOrEqualTo(String value) {
            addCriterion("inbound >=", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundLessThan(String value) {
            addCriterion("inbound <", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundLessThanOrEqualTo(String value) {
            addCriterion("inbound <=", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundLike(String value) {
            addCriterion("inbound like", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundNotLike(String value) {
            addCriterion("inbound not like", value, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundIn(List<String> values) {
            addCriterion("inbound in", values, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundNotIn(List<String> values) {
            addCriterion("inbound not in", values, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundBetween(String value1, String value2) {
            addCriterion("inbound between", value1, value2, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundNotBetween(String value1, String value2) {
            addCriterion("inbound not between", value1, value2, "inbound");
            return (Criteria) this;
        }

        public Criteria andInboundTimeIsNull() {
            addCriterion("inbound_time is null");
            return (Criteria) this;
        }

        public Criteria andInboundTimeIsNotNull() {
            addCriterion("inbound_time is not null");
            return (Criteria) this;
        }

        public Criteria andInboundTimeEqualTo(Date value) {
            addCriterion("inbound_time =", value, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeNotEqualTo(Date value) {
            addCriterion("inbound_time <>", value, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeGreaterThan(Date value) {
            addCriterion("inbound_time >", value, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("inbound_time >=", value, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeLessThan(Date value) {
            addCriterion("inbound_time <", value, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeLessThanOrEqualTo(Date value) {
            addCriterion("inbound_time <=", value, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeIn(List<Date> values) {
            addCriterion("inbound_time in", values, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeNotIn(List<Date> values) {
            addCriterion("inbound_time not in", values, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeBetween(Date value1, Date value2) {
            addCriterion("inbound_time between", value1, value2, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andInboundTimeNotBetween(Date value1, Date value2) {
            addCriterion("inbound_time not between", value1, value2, "inboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundIsNull() {
            addCriterion("outbound is null");
            return (Criteria) this;
        }

        public Criteria andOutboundIsNotNull() {
            addCriterion("outbound is not null");
            return (Criteria) this;
        }

        public Criteria andOutboundEqualTo(String value) {
            addCriterion("outbound =", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundNotEqualTo(String value) {
            addCriterion("outbound <>", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundGreaterThan(String value) {
            addCriterion("outbound >", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundGreaterThanOrEqualTo(String value) {
            addCriterion("outbound >=", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundLessThan(String value) {
            addCriterion("outbound <", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundLessThanOrEqualTo(String value) {
            addCriterion("outbound <=", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundLike(String value) {
            addCriterion("outbound like", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundNotLike(String value) {
            addCriterion("outbound not like", value, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundIn(List<String> values) {
            addCriterion("outbound in", values, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundNotIn(List<String> values) {
            addCriterion("outbound not in", values, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundBetween(String value1, String value2) {
            addCriterion("outbound between", value1, value2, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundNotBetween(String value1, String value2) {
            addCriterion("outbound not between", value1, value2, "outbound");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeIsNull() {
            addCriterion("outbound_time is null");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeIsNotNull() {
            addCriterion("outbound_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeEqualTo(Date value) {
            addCriterion("outbound_time =", value, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeNotEqualTo(Date value) {
            addCriterion("outbound_time <>", value, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeGreaterThan(Date value) {
            addCriterion("outbound_time >", value, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("outbound_time >=", value, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeLessThan(Date value) {
            addCriterion("outbound_time <", value, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeLessThanOrEqualTo(Date value) {
            addCriterion("outbound_time <=", value, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeIn(List<Date> values) {
            addCriterion("outbound_time in", values, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeNotIn(List<Date> values) {
            addCriterion("outbound_time not in", values, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeBetween(Date value1, Date value2) {
            addCriterion("outbound_time between", value1, value2, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andOutboundTimeNotBetween(Date value1, Date value2) {
            addCriterion("outbound_time not between", value1, value2, "outboundTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeIsNull() {
            addCriterion("processing_time is null");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeIsNotNull() {
            addCriterion("processing_time is not null");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeEqualTo(Integer value) {
            addCriterion("processing_time =", value, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeNotEqualTo(Integer value) {
            addCriterion("processing_time <>", value, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeGreaterThan(Integer value) {
            addCriterion("processing_time >", value, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("processing_time >=", value, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeLessThan(Integer value) {
            addCriterion("processing_time <", value, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeLessThanOrEqualTo(Integer value) {
            addCriterion("processing_time <=", value, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeIn(List<Integer> values) {
            addCriterion("processing_time in", values, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeNotIn(List<Integer> values) {
            addCriterion("processing_time not in", values, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeBetween(Integer value1, Integer value2) {
            addCriterion("processing_time between", value1, value2, "processingTime");
            return (Criteria) this;
        }

        public Criteria andProcessingTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("processing_time not between", value1, value2, "processingTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_ws
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 26 12:07:01 ICT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_ws
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}