package com.tti.accscms.domain.movement;

import java.util.Date;

public class ShipmentSearchCondition3 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.faulty_status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String faultyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.faulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date faultyDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.unfaulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date unfaultyDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.user_faulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String userFaulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.user_unfaulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String userUnfaulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String flightNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.permit_status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String permitStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Date flightDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String mawb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String hawb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.shed_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String shedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.abil_goods_description
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String abilGoodsDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Double grossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String grossWeightUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private Integer numberOfPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipment_search_condition_3.number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    private String numberOfPackageUnit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.id
     *
     * @return the value of shipment_search_condition_3.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.id
     *
     * @param id the value for shipment_search_condition_3.id
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.faulty_status
     *
     * @return the value of shipment_search_condition_3.faulty_status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getFaultyStatus() {
        return faultyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.faulty_status
     *
     * @param faultyStatus the value for shipment_search_condition_3.faulty_status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFaultyStatus(String faultyStatus) {
        this.faultyStatus = faultyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.faulty_date_time
     *
     * @return the value of shipment_search_condition_3.faulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getFaultyDateTime() {
        return faultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.faulty_date_time
     *
     * @param faultyDateTime the value for shipment_search_condition_3.faulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFaultyDateTime(Date faultyDateTime) {
        this.faultyDateTime = faultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.unfaulty_date_time
     *
     * @return the value of shipment_search_condition_3.unfaulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getUnfaultyDateTime() {
        return unfaultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.unfaulty_date_time
     *
     * @param unfaultyDateTime the value for shipment_search_condition_3.unfaulty_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setUnfaultyDateTime(Date unfaultyDateTime) {
        this.unfaultyDateTime = unfaultyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.user_faulty
     *
     * @return the value of shipment_search_condition_3.user_faulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getUserFaulty() {
        return userFaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.user_faulty
     *
     * @param userFaulty the value for shipment_search_condition_3.user_faulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setUserFaulty(String userFaulty) {
        this.userFaulty = userFaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.user_unfaulty
     *
     * @return the value of shipment_search_condition_3.user_unfaulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getUserUnfaulty() {
        return userUnfaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.user_unfaulty
     *
     * @param userUnfaulty the value for shipment_search_condition_3.user_unfaulty
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setUserUnfaulty(String userUnfaulty) {
        this.userUnfaulty = userUnfaulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.flight_no
     *
     * @return the value of shipment_search_condition_3.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getFlightNo() {
        return flightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.flight_no
     *
     * @param flightNo the value for shipment_search_condition_3.flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.permit_status
     *
     * @return the value of shipment_search_condition_3.permit_status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getPermitStatus() {
        return permitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.permit_status
     *
     * @param permitStatus the value for shipment_search_condition_3.permit_status
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setPermitStatus(String permitStatus) {
        this.permitStatus = permitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.flight_date
     *
     * @return the value of shipment_search_condition_3.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Date getFlightDate() {
        return flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.flight_date
     *
     * @param flightDate the value for shipment_search_condition_3.flight_date
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.mawb
     *
     * @return the value of shipment_search_condition_3.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getMawb() {
        return mawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.mawb
     *
     * @param mawb the value for shipment_search_condition_3.mawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setMawb(String mawb) {
        this.mawb = mawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.hawb
     *
     * @return the value of shipment_search_condition_3.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getHawb() {
        return hawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.hawb
     *
     * @param hawb the value for shipment_search_condition_3.hawb
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setHawb(String hawb) {
        this.hawb = hawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.shed_no
     *
     * @return the value of shipment_search_condition_3.shed_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getShedNo() {
        return shedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.shed_no
     *
     * @param shedNo the value for shipment_search_condition_3.shed_no
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setShedNo(String shedNo) {
        this.shedNo = shedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.abil_goods_description
     *
     * @return the value of shipment_search_condition_3.abil_goods_description
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getAbilGoodsDescription() {
        return abilGoodsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.abil_goods_description
     *
     * @param abilGoodsDescription the value for shipment_search_condition_3.abil_goods_description
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setAbilGoodsDescription(String abilGoodsDescription) {
        this.abilGoodsDescription = abilGoodsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.gross_weight
     *
     * @return the value of shipment_search_condition_3.gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Double getGrossWeight() {
        return grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.gross_weight
     *
     * @param grossWeight the value for shipment_search_condition_3.gross_weight
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setGrossWeight(Double grossWeight) {
        this.grossWeight = grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.gross_weight_unit
     *
     * @return the value of shipment_search_condition_3.gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getGrossWeightUnit() {
        return grossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.gross_weight_unit
     *
     * @param grossWeightUnit the value for shipment_search_condition_3.gross_weight_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setGrossWeightUnit(String grossWeightUnit) {
        this.grossWeightUnit = grossWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.number_of_package
     *
     * @return the value of shipment_search_condition_3.number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public Integer getNumberOfPackage() {
        return numberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.number_of_package
     *
     * @param numberOfPackage the value for shipment_search_condition_3.number_of_package
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setNumberOfPackage(Integer numberOfPackage) {
        this.numberOfPackage = numberOfPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipment_search_condition_3.number_of_package_unit
     *
     * @return the value of shipment_search_condition_3.number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public String getNumberOfPackageUnit() {
        return numberOfPackageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipment_search_condition_3.number_of_package_unit
     *
     * @param numberOfPackageUnit the value for shipment_search_condition_3.number_of_package_unit
     *
     * @mbggenerated Wed Dec 26 12:07:01 ICT 2012
     */
    public void setNumberOfPackageUnit(String numberOfPackageUnit) {
        this.numberOfPackageUnit = numberOfPackageUnit;
    }
}