package com.tti.accscms.mapper.manifest;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.datasource.DataSourceUtils;

import com.tti.accscms.dao.DaoException;
import com.tti.accscms.dao.manifest.AirWaybillControlHistoryDao;

import com.tti.accscms.domain.manifest.AirWaybillControlHistory;
import com.tti.accscms.domain.manifest.AirWaybillControlHistoryExample;

/**
 * This class was generated by Generator.
 * This class corresponds to the database table abil_control_his
 */
public class AirWaybillControlHistoryDaoImpl implements AirWaybillControlHistoryDao {

	private static final Logger logger = LoggerFactory.getLogger(AirWaybillControlHistoryDaoImpl.class);
	
	private static final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	
    private DataSource dataSource;
    
    public void setDataSource(DataSource dataSource) {
    	this.dataSource = dataSource;
    }
		
	private static void setPreparedStatementValues(PreparedStatement ps, AirWaybillControlHistory airWaybillControlHistory) throws SQLException {
		
		if (airWaybillControlHistory.getId() != null) {
			ps.setInt(1, airWaybillControlHistory.getId());
		} else {
			ps.setNull(1, java.sql.Types.INTEGER);
		}

		if (airWaybillControlHistory.getId2() != null) {
			ps.setInt(2, airWaybillControlHistory.getId2());
		} else {
			ps.setNull(2, java.sql.Types.INTEGER);
		}

		if (airWaybillControlHistory.getAbilControlId() != null) {
			ps.setInt(3, airWaybillControlHistory.getAbilControlId());
		} else {
			ps.setNull(3, java.sql.Types.INTEGER);
		}

		if (airWaybillControlHistory.getReferenceNumber() != null) {
			ps.setString(4, airWaybillControlHistory.getReferenceNumber());
		} else {
			ps.setNull(4, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getReceivedControlNumber() != null) {
			ps.setString(5, airWaybillControlHistory.getReceivedControlNumber());
		} else {
			ps.setNull(5, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getMawb() != null) {
			ps.setString(6, airWaybillControlHistory.getMawb());
		} else {
			ps.setNull(6, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getFreightForwarderTaxNumber() != null) {
			ps.setString(7, airWaybillControlHistory.getFreightForwarderTaxNumber());
		} else {
			ps.setNull(7, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getFreightForwarderBranch() != null) {
			ps.setInt(8, airWaybillControlHistory.getFreightForwarderBranch());
		} else {
			ps.setNull(8, java.sql.Types.INTEGER);
		}

		if (airWaybillControlHistory.getProcessingIndicator() != null) {
			ps.setString(9, airWaybillControlHistory.getProcessingIndicator());
		} else {
			ps.setNull(9, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getOriginCountryCode() != null) {
			ps.setString(10, airWaybillControlHistory.getOriginCountryCode());
		} else {
			ps.setNull(10, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getPortOfLoading() != null) {
			ps.setString(11, airWaybillControlHistory.getPortOfLoading());
		} else {
			ps.setNull(11, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getPortOfDischarge() != null) {
			ps.setString(12, airWaybillControlHistory.getPortOfDischarge());
		} else {
			ps.setNull(12, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getPlaceOfReceipt() != null) {
			ps.setString(13, airWaybillControlHistory.getPlaceOfReceipt());
		} else {
			ps.setNull(13, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getPlaceOfDelivery() != null) {
			ps.setString(14, airWaybillControlHistory.getPlaceOfDelivery());
		} else {
			ps.setNull(14, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getShedNo() != null) {
			ps.setInt(15, airWaybillControlHistory.getShedNo());
		} else {
			ps.setNull(15, java.sql.Types.INTEGER);
		}

		if (airWaybillControlHistory.getMessageFunction() != null) {
			ps.setString(16, airWaybillControlHistory.getMessageFunction());
		} else {
			ps.setNull(16, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getFreightCharges() != null) {
			ps.setString(17, airWaybillControlHistory.getFreightCharges());
		} else {
			ps.setNull(17, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getOtherCharges() != null) {
			ps.setString(18, airWaybillControlHistory.getOtherCharges());
		} else {
			ps.setNull(18, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getFreightAmountForeign() != null) {
			ps.setDouble(19, airWaybillControlHistory.getFreightAmountForeign());
		} else {
			ps.setNull(19, java.sql.Types.DOUBLE);
		}

		if (airWaybillControlHistory.getFreightCurrencyCode() != null) {
			ps.setString(20, airWaybillControlHistory.getFreightCurrencyCode());
		} else {
			ps.setNull(20, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getTermOfPaymentFreight() != null) {
			ps.setString(21, airWaybillControlHistory.getTermOfPaymentFreight());
		} else {
			ps.setNull(21, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getRegistrationId() != null) {
			ps.setString(22, airWaybillControlHistory.getRegistrationId());
		} else {
			ps.setNull(22, java.sql.Types.VARCHAR);
		}

		if (airWaybillControlHistory.getModifiedDateTime() != null) {
			ps.setTimestamp(23, new java.sql.Timestamp(airWaybillControlHistory.getModifiedDateTime().getTime()));
		} else {
			ps.setTimestamp(23, new java.sql.Timestamp(System.currentTimeMillis()));
		}

		if (airWaybillControlHistory.getType() != null) {
			ps.setInt(24, airWaybillControlHistory.getType());
		} else {
			ps.setNull(24, java.sql.Types.INTEGER);
		}

	}

		
	private static AirWaybillControlHistory createInstanceFromResultSet(ResultSet rs) throws SQLException {
		AirWaybillControlHistory airWaybillControlHistory = new AirWaybillControlHistory();
		
		Integer col1 = rs.getInt("id");
		airWaybillControlHistory.setId(rs.wasNull() ? null : col1);

		Integer col2 = rs.getInt("id2");
		airWaybillControlHistory.setId2(rs.wasNull() ? null : col2);

		Integer col3 = rs.getInt("abil_control_id");
		airWaybillControlHistory.setAbilControlId(rs.wasNull() ? null : col3);

		String col4 = rs.getString("reference_number");
		airWaybillControlHistory.setReferenceNumber(rs.wasNull() ? null : col4);

		String col5 = rs.getString("received_control_number");
		airWaybillControlHistory.setReceivedControlNumber(rs.wasNull() ? null : col5);

		String col6 = rs.getString("mawb");
		airWaybillControlHistory.setMawb(rs.wasNull() ? null : col6);

		String col7 = rs.getString("freight_forwarder_tax_number");
		airWaybillControlHistory.setFreightForwarderTaxNumber(rs.wasNull() ? null : col7);

		Integer col8 = rs.getInt("freight_forwarder_branch");
		airWaybillControlHistory.setFreightForwarderBranch(rs.wasNull() ? null : col8);

		String col9 = rs.getString("processing_indicator");
		airWaybillControlHistory.setProcessingIndicator(rs.wasNull() ? null : col9);

		String col10 = rs.getString("origin_country_code");
		airWaybillControlHistory.setOriginCountryCode(rs.wasNull() ? null : col10);

		String col11 = rs.getString("port_of_loading");
		airWaybillControlHistory.setPortOfLoading(rs.wasNull() ? null : col11);

		String col12 = rs.getString("port_of_discharge");
		airWaybillControlHistory.setPortOfDischarge(rs.wasNull() ? null : col12);

		String col13 = rs.getString("place_of_receipt");
		airWaybillControlHistory.setPlaceOfReceipt(rs.wasNull() ? null : col13);

		String col14 = rs.getString("place_of_delivery");
		airWaybillControlHistory.setPlaceOfDelivery(rs.wasNull() ? null : col14);

		Integer col15 = rs.getInt("shed_no");
		airWaybillControlHistory.setShedNo(rs.wasNull() ? null : col15);

		String col16 = rs.getString("message_function");
		airWaybillControlHistory.setMessageFunction(rs.wasNull() ? null : col16);

		String col17 = rs.getString("freight_charges");
		airWaybillControlHistory.setFreightCharges(rs.wasNull() ? null : col17);

		String col18 = rs.getString("other_charges");
		airWaybillControlHistory.setOtherCharges(rs.wasNull() ? null : col18);

		Double col19 = rs.getDouble("freight_amount_foreign");
		airWaybillControlHistory.setFreightAmountForeign(rs.wasNull() ? null : col19);

		String col20 = rs.getString("freight_currency_code");
		airWaybillControlHistory.setFreightCurrencyCode(rs.wasNull() ? null : col20);

		String col21 = rs.getString("term_of_payment_freight");
		airWaybillControlHistory.setTermOfPaymentFreight(rs.wasNull() ? null : col21);

		String col22 = rs.getString("registration_id");
		airWaybillControlHistory.setRegistrationId(rs.wasNull() ? null : col22);

		java.sql.Timestamp col23 = rs.getTimestamp("modified_date_time");
		airWaybillControlHistory.setModifiedDateTime(rs.wasNull() ? null : new java.util.Date(col23.getTime()));

		Integer col24 = rs.getInt("type");
		airWaybillControlHistory.setType(rs.wasNull() ? null : col24);


		return airWaybillControlHistory;
	}  

		
	@Override
	public int insert(AirWaybillControlHistory airWaybillControlHistory) throws DaoException {
		if (airWaybillControlHistory == null) {
			throw new DaoException("Cannot insert abil_control_his with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("insert into abil_control_his(`id`,`id2`,`abil_control_id`,`reference_number`,`received_control_number`,`mawb`,`freight_forwarder_tax_number`,`freight_forwarder_branch`,`processing_indicator`,`origin_country_code`,`port_of_loading`,`port_of_discharge`,`place_of_receipt`,`place_of_delivery`,`shed_no`,`message_function`,`freight_charges`,`other_charges`,`freight_amount_foreign`,`freight_currency_code`,`term_of_payment_freight`,`registration_id`,`modified_date_time`,`type`) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            AirWaybillControlHistoryDaoImpl.setPreparedStatementValues(ps, airWaybillControlHistory);
			ps.setNull(1, java.sql.Types.INTEGER);
            ps.execute();
			int id = -1;
			ResultSet rs = ps.getGeneratedKeys();
			if (rs.next()) {
				id = rs.getInt(1);
			}
			rs.close();
			ps.close();

			logger.info("DB:INSERT abil_control_his[id=" + id + "]");

			return id;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int count() throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
			Statement stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select count(*) from abil_control_his");
			
			int count = -1;
			if (rs.next()) { 
				count = rs.getInt(1);
			}
			rs.close();
			stmt.close();
			
			logger.debug("DB:COUNT abil_control_his => " + count);
			
			return count;
		} catch (SQLException e) {
			throw new DaoException(e);
		}
	}

	@Override
	public AirWaybillControlHistory findById(Integer id) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("select `id`,`id2`,`abil_control_id`,`reference_number`,`received_control_number`,`mawb`,`freight_forwarder_tax_number`,`freight_forwarder_branch`,`processing_indicator`,`origin_country_code`,`port_of_loading`,`port_of_discharge`,`place_of_receipt`,`place_of_delivery`,`shed_no`,`message_function`,`freight_charges`,`other_charges`,`freight_amount_foreign`,`freight_currency_code`,`term_of_payment_freight`,`registration_id`,`modified_date_time`,`type` from abil_control_his where id=?");
            ps.setInt(1, id);
            
            logger.debug("DB:FIND abil_control_his[id=" + id + "]");

            ResultSet rs = ps.executeQuery();
            AirWaybillControlHistory instance = null;
            if (rs.next()) {
                instance = AirWaybillControlHistoryDaoImpl.createInstanceFromResultSet(rs);
            }
            rs.close();
            ps.close();

            return instance;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int update(AirWaybillControlHistory airWaybillControlHistory) throws DaoException {
		if (airWaybillControlHistory == null) {
			throw new DaoException("Cannot insert abil_control_his with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("update abil_control_his set `id`=?,`id2`=?,`abil_control_id`=?,`reference_number`=?,`received_control_number`=?,`mawb`=?,`freight_forwarder_tax_number`=?,`freight_forwarder_branch`=?,`processing_indicator`=?,`origin_country_code`=?,`port_of_loading`=?,`port_of_discharge`=?,`place_of_receipt`=?,`place_of_delivery`=?,`shed_no`=?,`message_function`=?,`freight_charges`=?,`other_charges`=?,`freight_amount_foreign`=?,`freight_currency_code`=?,`term_of_payment_freight`=?,`registration_id`=?,`modified_date_time`=?,`type`=? where id=?");
            AirWaybillControlHistoryDaoImpl.setPreparedStatementValues(ps, airWaybillControlHistory);
            ps.setInt(25, airWaybillControlHistory.getId());
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:UPDATE abil_control_his[id=" + airWaybillControlHistory.getId() + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int deleteById(Integer id) throws DaoException {
		 try {
		 	Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("delete from abil_control_his where id=?");
            ps.setInt(1, id);
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:DELETE abil_control_his[id=" + id + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}

	
		
	private static String buildClause(AirWaybillControlHistoryExample airWaybillControlHistoryExample) {
		StringBuilder builder = new StringBuilder();
		boolean firstO = true;
		for (AirWaybillControlHistoryExample.Criteria criteria : airWaybillControlHistoryExample.getOredCriteria()) {
			if (firstO) {
				firstO = false;
			} else {
				builder.append(" or ");
			}
			
			if (criteria.isValid()) {
				builder.append('(');
				boolean first = true;
				for (AirWaybillControlHistoryExample.Criterion criterion : criteria.getAllCriteria()) {
					if (first) {
						first = false;
					} else {
						builder.append(" and ");
					}
					
					if (criterion.isNoValue()) {
						builder.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isBetweenValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
						
						builder.append(" and ");
						builder.append("'");
						if (criterion.getSecondValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getSecondValue()));
						} else {
							builder.append(criterion.getSecondValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isListValue()) {
						builder.append(criterion.getCondition());
						builder.append('(');
						List<?> items = (List<?>) criterion.getValue();
						boolean firstC = true;
						for (Object item : items) {
							if (firstC) {
								firstC = false;
							} else {
								builder.append(", ");
							}
							builder.append("'");
							if (item instanceof java.util.Date) {
								builder.append(dateFormat.format(item));
							} else {
								builder.append(item.toString().replace("'", "\'"));
							}
							builder.append("'");
						}
						builder.append(')');
					}
				}
				builder.append(')');
			}
		}
		
		String clause = firstO ? "" : " where " + builder.toString();
		
		if (airWaybillControlHistoryExample.getOrderByClause() != null && !airWaybillControlHistoryExample.getOrderByClause().isEmpty()) {
			clause += " order by " + airWaybillControlHistoryExample.getOrderByClause();
		}
		
		return clause;
	}
	
	@Override
	public int countByAirWaybillControlHistoryExample(AirWaybillControlHistoryExample airWaybillControlHistoryExample) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();

			String clause = AirWaybillControlHistoryDaoImpl.buildClause(airWaybillControlHistoryExample);			
            ResultSet rs = stmt.executeQuery("select" + (airWaybillControlHistoryExample.isDistinct() ? " distinct " : " ") + "count(*) from abil_control_his" + clause);
            int count = -1;
            if (rs.next()) {
            	count = rs.getInt(1);
           	}
            rs.close();
            stmt.close();
            
            logger.debug("DB:COUNT abil_control_his[distinct=" + airWaybillControlHistoryExample.isDistinct() + ",clause=" + clause + "] => " + count);

            return count;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public AirWaybillControlHistory findByAirWaybillControlHistoryExample(AirWaybillControlHistoryExample airWaybillControlHistoryExample) throws DaoException {
		List<AirWaybillControlHistory> res = this.findAllByAirWaybillControlHistoryExample(airWaybillControlHistoryExample, 0, 1);
		if (res.size() > 0) {
			return res.get(0);
		} else {
			return null;
		}
	}
	
	@Override
    public List<AirWaybillControlHistory> findAllByAirWaybillControlHistoryExample(AirWaybillControlHistoryExample airWaybillControlHistoryExample) throws DaoException {
    	return this.findAllByAirWaybillControlHistoryExample(airWaybillControlHistoryExample, 0, 2000);
    }
    
    @Override
    public List<AirWaybillControlHistory> findAllByAirWaybillControlHistoryExample(AirWaybillControlHistoryExample airWaybillControlHistoryExample, int limit) throws DaoException {
    	return this.findAllByAirWaybillControlHistoryExample(airWaybillControlHistoryExample, 0, limit);
    }
    
    @Override
    public List<AirWaybillControlHistory> findAllByAirWaybillControlHistoryExample(AirWaybillControlHistoryExample airWaybillControlHistoryExample, int offset, int limit) throws DaoException {
    	try {
    		Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();
            String clause = AirWaybillControlHistoryDaoImpl.buildClause(airWaybillControlHistoryExample) + " limit " + offset + "," + limit;
            
            logger.debug("DB:FIND abil_control_his[distinct=" + airWaybillControlHistoryExample.isDistinct() + ",clause=" + clause + "]");
            
            ResultSet rs = stmt.executeQuery("select" + (airWaybillControlHistoryExample.isDistinct() ? " distinct " : " ") + "`id`,`id2`,`abil_control_id`,`reference_number`,`received_control_number`,`mawb`,`freight_forwarder_tax_number`,`freight_forwarder_branch`,`processing_indicator`,`origin_country_code`,`port_of_loading`,`port_of_discharge`,`place_of_receipt`,`place_of_delivery`,`shed_no`,`message_function`,`freight_charges`,`other_charges`,`freight_amount_foreign`,`freight_currency_code`,`term_of_payment_freight`,`registration_id`,`modified_date_time`,`type` from abil_control_his" + clause);

            List<AirWaybillControlHistory> list = new ArrayList<AirWaybillControlHistory>();
            while (rs.next()) {
                list.add(AirWaybillControlHistoryDaoImpl.createInstanceFromResultSet(rs));
            }
            rs.close();
            stmt.close();

            return list;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}

}
