package com.tti.accscms.mapper.movement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.datasource.DataSourceUtils;

import com.tti.accscms.dao.DaoException;
import com.tti.accscms.dao.movement.BlockStatusLogDao;

import com.tti.accscms.domain.movement.BlockStatusLog;
import com.tti.accscms.domain.movement.BlockStatusLogExample;

/**
 * This class was generated by Generator.
 * This class corresponds to the database table block_status_log
 */
public class BlockStatusLogDaoImpl implements BlockStatusLogDao {

	private static final Logger logger = LoggerFactory.getLogger(BlockStatusLogDaoImpl.class);
	
	private static final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	
    private DataSource dataSource;
    
    public void setDataSource(DataSource dataSource) {
    	this.dataSource = dataSource;
    }
		
	private static void setPreparedStatementValues(PreparedStatement ps, BlockStatusLog blockStatusLog) throws SQLException {
		
		if (blockStatusLog.getId() != null) {
			ps.setInt(1, blockStatusLog.getId());
		} else {
			ps.setNull(1, java.sql.Types.INTEGER);
		}

		if (blockStatusLog.getId2() != null) {
			ps.setInt(2, blockStatusLog.getId2());
		} else {
			ps.setNull(2, java.sql.Types.INTEGER);
		}

		if (blockStatusLog.getBlockStatusId() != null) {
			ps.setInt(3, blockStatusLog.getBlockStatusId());
		} else {
			ps.setNull(3, java.sql.Types.INTEGER);
		}

		if (blockStatusLog.getDesc() != null) {
			ps.setString(4, blockStatusLog.getDesc());
		} else {
			ps.setNull(4, java.sql.Types.VARCHAR);
		}

		if (blockStatusLog.getDateTime() != null) {
			ps.setTimestamp(5, new java.sql.Timestamp(blockStatusLog.getDateTime().getTime()));
		} else {
			ps.setNull(5, java.sql.Types.TIMESTAMP);
		}

		if (blockStatusLog.getUser() != null) {
			ps.setString(6, blockStatusLog.getUser());
		} else {
			ps.setNull(6, java.sql.Types.VARCHAR);
		}

	}

		
	private static BlockStatusLog createInstanceFromResultSet(ResultSet rs) throws SQLException {
		BlockStatusLog blockStatusLog = new BlockStatusLog();
		
		Integer col1 = rs.getInt("id");
		blockStatusLog.setId(rs.wasNull() ? null : col1);

		Integer col2 = rs.getInt("id2");
		blockStatusLog.setId2(rs.wasNull() ? null : col2);

		Integer col3 = rs.getInt("block_status_id");
		blockStatusLog.setBlockStatusId(rs.wasNull() ? null : col3);

		String col4 = rs.getString("desc");
		blockStatusLog.setDesc(rs.wasNull() ? null : col4);

		java.sql.Timestamp col5 = rs.getTimestamp("date_time");
		blockStatusLog.setDateTime(rs.wasNull() ? null : new java.util.Date(col5.getTime()));

		String col6 = rs.getString("user");
		blockStatusLog.setUser(rs.wasNull() ? null : col6);


		return blockStatusLog;
	}  

		
	@Override
	public int insert(BlockStatusLog blockStatusLog) throws DaoException {
		if (blockStatusLog == null) {
			throw new DaoException("Cannot insert block_status_log with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("insert into block_status_log(`id`,`id2`,`block_status_id`,`desc`,`date_time`,`user`) values(?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            BlockStatusLogDaoImpl.setPreparedStatementValues(ps, blockStatusLog);
			ps.setNull(1, java.sql.Types.INTEGER);
            ps.execute();
			int id = -1;
			ResultSet rs = ps.getGeneratedKeys();
			if (rs.next()) {
				id = rs.getInt(1);
			}
			rs.close();
			ps.close();

			logger.info("DB:INSERT block_status_log[id=" + id + "]");

			return id;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int count() throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
			Statement stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select count(*) from block_status_log");
			
			int count = -1;
			if (rs.next()) { 
				count = rs.getInt(1);
			}
			rs.close();
			stmt.close();
			
			logger.debug("DB:COUNT block_status_log => " + count);
			
			return count;
		} catch (SQLException e) {
			throw new DaoException(e);
		}
	}

	@Override
	public BlockStatusLog findById(Integer id) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("select `id`,`id2`,`block_status_id`,`desc`,`date_time`,`user` from block_status_log where id=?");
            ps.setInt(1, id);
            
            logger.debug("DB:FIND block_status_log[id=" + id + "]");

            ResultSet rs = ps.executeQuery();
            BlockStatusLog instance = null;
            if (rs.next()) {
                instance = BlockStatusLogDaoImpl.createInstanceFromResultSet(rs);
            }
            rs.close();
            ps.close();

            return instance;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int update(BlockStatusLog blockStatusLog) throws DaoException {
		if (blockStatusLog == null) {
			throw new DaoException("Cannot insert block_status_log with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("update block_status_log set `id`=?,`id2`=?,`block_status_id`=?,`desc`=?,`date_time`=?,`user`=? where id=?");
            BlockStatusLogDaoImpl.setPreparedStatementValues(ps, blockStatusLog);
            ps.setInt(7, blockStatusLog.getId());
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:UPDATE block_status_log[id=" + blockStatusLog.getId() + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int deleteById(Integer id) throws DaoException {
		 try {
		 	Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("delete from block_status_log where id=?");
            ps.setInt(1, id);
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:DELETE block_status_log[id=" + id + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}

	
		
	private static String buildClause(BlockStatusLogExample blockStatusLogExample) {
		StringBuilder builder = new StringBuilder();
		boolean firstO = true;
		for (BlockStatusLogExample.Criteria criteria : blockStatusLogExample.getOredCriteria()) {
			if (firstO) {
				firstO = false;
			} else {
				builder.append(" or ");
			}
			
			if (criteria.isValid()) {
				builder.append('(');
				boolean first = true;
				for (BlockStatusLogExample.Criterion criterion : criteria.getAllCriteria()) {
					if (first) {
						first = false;
					} else {
						builder.append(" and ");
					}
					
					if (criterion.isNoValue()) {
						builder.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isBetweenValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
						
						builder.append(" and ");
						builder.append("'");
						if (criterion.getSecondValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getSecondValue()));
						} else {
							builder.append(criterion.getSecondValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isListValue()) {
						builder.append(criterion.getCondition());
						builder.append('(');
						List<?> items = (List<?>) criterion.getValue();
						boolean firstC = true;
						for (Object item : items) {
							if (firstC) {
								firstC = false;
							} else {
								builder.append(", ");
							}
							builder.append("'");
							if (item instanceof java.util.Date) {
								builder.append(dateFormat.format(item));
							} else {
								builder.append(item.toString().replace("'", "\'"));
							}
							builder.append("'");
						}
						builder.append(')');
					}
				}
				builder.append(')');
			}
		}
		
		String clause = firstO ? "" : " where " + builder.toString();
		
		if (blockStatusLogExample.getOrderByClause() != null && !blockStatusLogExample.getOrderByClause().isEmpty()) {
			clause += " order by " + blockStatusLogExample.getOrderByClause();
		}
		
		return clause;
	}
	
	@Override
	public int countByBlockStatusLogExample(BlockStatusLogExample blockStatusLogExample) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();

			String clause = BlockStatusLogDaoImpl.buildClause(blockStatusLogExample);			
            ResultSet rs = stmt.executeQuery("select" + (blockStatusLogExample.isDistinct() ? " distinct " : " ") + "count(*) from block_status_log" + clause);
            int count = -1;
            if (rs.next()) {
            	count = rs.getInt(1);
           	}
            rs.close();
            stmt.close();
            
            logger.debug("DB:COUNT block_status_log[distinct=" + blockStatusLogExample.isDistinct() + ",clause=" + clause + "] => " + count);

            return count;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public BlockStatusLog findByBlockStatusLogExample(BlockStatusLogExample blockStatusLogExample) throws DaoException {
		List<BlockStatusLog> res = this.findAllByBlockStatusLogExample(blockStatusLogExample, 0, 1);
		if (res.size() > 0) {
			return res.get(0);
		} else {
			return null;
		}
	}
	
	@Override
    public List<BlockStatusLog> findAllByBlockStatusLogExample(BlockStatusLogExample blockStatusLogExample) throws DaoException {
    	return this.findAllByBlockStatusLogExample(blockStatusLogExample, 0, 2000);
    }
    
    @Override
    public List<BlockStatusLog> findAllByBlockStatusLogExample(BlockStatusLogExample blockStatusLogExample, int limit) throws DaoException {
    	return this.findAllByBlockStatusLogExample(blockStatusLogExample, 0, limit);
    }
    
    @Override
    public List<BlockStatusLog> findAllByBlockStatusLogExample(BlockStatusLogExample blockStatusLogExample, int offset, int limit) throws DaoException {
    	try {
    		Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();
            String clause = BlockStatusLogDaoImpl.buildClause(blockStatusLogExample) + " limit " + offset + "," + limit;
            
            logger.debug("DB:FIND block_status_log[distinct=" + blockStatusLogExample.isDistinct() + ",clause=" + clause + "]");
            
            ResultSet rs = stmt.executeQuery("select" + (blockStatusLogExample.isDistinct() ? " distinct " : " ") + "`id`,`id2`,`block_status_id`,`desc`,`date_time`,`user` from block_status_log" + clause);

            List<BlockStatusLog> list = new ArrayList<BlockStatusLog>();
            while (rs.next()) {
                list.add(BlockStatusLogDaoImpl.createInstanceFromResultSet(rs));
            }
            rs.close();
            stmt.close();

            return list;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}

}
