package com.tti.accscms.mapper.movement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.datasource.DataSourceUtils;

import com.tti.accscms.dao.DaoException;
import com.tti.accscms.dao.movement.ChangeAirportLogDao;

import com.tti.accscms.domain.movement.ChangeAirportLog;
import com.tti.accscms.domain.movement.ChangeAirportLogExample;

/**
 * This class was generated by Generator.
 * This class corresponds to the database table change_airport_log
 */
public class ChangeAirportLogDaoImpl implements ChangeAirportLogDao {

	private static final Logger logger = LoggerFactory.getLogger(ChangeAirportLogDaoImpl.class);
	
	private static final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	
    private DataSource dataSource;
    
    public void setDataSource(DataSource dataSource) {
    	this.dataSource = dataSource;
    }
		
	private static void setPreparedStatementValues(PreparedStatement ps, ChangeAirportLog changeAirportLog) throws SQLException {
		
		if (changeAirportLog.getId() != null) {
			ps.setInt(1, changeAirportLog.getId());
		} else {
			ps.setNull(1, java.sql.Types.INTEGER);
		}

		if (changeAirportLog.getId2() != null) {
			ps.setInt(2, changeAirportLog.getId2());
		} else {
			ps.setNull(2, java.sql.Types.INTEGER);
		}

		if (changeAirportLog.getChangeAirportId() != null) {
			ps.setInt(3, changeAirportLog.getChangeAirportId());
		} else {
			ps.setNull(3, java.sql.Types.INTEGER);
		}

		if (changeAirportLog.getUser() != null) {
			ps.setString(4, changeAirportLog.getUser());
		} else {
			ps.setNull(4, java.sql.Types.VARCHAR);
		}

		if (changeAirportLog.getDesc() != null) {
			ps.setString(5, changeAirportLog.getDesc());
		} else {
			ps.setNull(5, java.sql.Types.VARCHAR);
		}

		if (changeAirportLog.getDateTime() != null) {
			ps.setTimestamp(6, new java.sql.Timestamp(changeAirportLog.getDateTime().getTime()));
		} else {
			ps.setNull(6, java.sql.Types.TIMESTAMP);
		}

	}

		
	private static ChangeAirportLog createInstanceFromResultSet(ResultSet rs) throws SQLException {
		ChangeAirportLog changeAirportLog = new ChangeAirportLog();
		
		Integer col1 = rs.getInt("id");
		changeAirportLog.setId(rs.wasNull() ? null : col1);

		Integer col2 = rs.getInt("id2");
		changeAirportLog.setId2(rs.wasNull() ? null : col2);

		Integer col3 = rs.getInt("change_airport_id");
		changeAirportLog.setChangeAirportId(rs.wasNull() ? null : col3);

		String col4 = rs.getString("user");
		changeAirportLog.setUser(rs.wasNull() ? null : col4);

		String col5 = rs.getString("desc");
		changeAirportLog.setDesc(rs.wasNull() ? null : col5);

		java.sql.Timestamp col6 = rs.getTimestamp("date_time");
		changeAirportLog.setDateTime(rs.wasNull() ? null : new java.util.Date(col6.getTime()));


		return changeAirportLog;
	}  

		
	@Override
	public int insert(ChangeAirportLog changeAirportLog) throws DaoException {
		if (changeAirportLog == null) {
			throw new DaoException("Cannot insert change_airport_log with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("insert into change_airport_log(`id`,`id2`,`change_airport_id`,`user`,`desc`,`date_time`) values(?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            ChangeAirportLogDaoImpl.setPreparedStatementValues(ps, changeAirportLog);
			ps.setNull(1, java.sql.Types.INTEGER);
            ps.execute();
			int id = -1;
			ResultSet rs = ps.getGeneratedKeys();
			if (rs.next()) {
				id = rs.getInt(1);
			}
			rs.close();
			ps.close();

			logger.info("DB:INSERT change_airport_log[id=" + id + "]");

			return id;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int count() throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
			Statement stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select count(*) from change_airport_log");
			
			int count = -1;
			if (rs.next()) { 
				count = rs.getInt(1);
			}
			rs.close();
			stmt.close();
			
			logger.debug("DB:COUNT change_airport_log => " + count);
			
			return count;
		} catch (SQLException e) {
			throw new DaoException(e);
		}
	}

	@Override
	public ChangeAirportLog findById(Integer id) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("select `id`,`id2`,`change_airport_id`,`user`,`desc`,`date_time` from change_airport_log where id=?");
            ps.setInt(1, id);
            
            logger.debug("DB:FIND change_airport_log[id=" + id + "]");

            ResultSet rs = ps.executeQuery();
            ChangeAirportLog instance = null;
            if (rs.next()) {
                instance = ChangeAirportLogDaoImpl.createInstanceFromResultSet(rs);
            }
            rs.close();
            ps.close();

            return instance;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int update(ChangeAirportLog changeAirportLog) throws DaoException {
		if (changeAirportLog == null) {
			throw new DaoException("Cannot insert change_airport_log with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("update change_airport_log set `id`=?,`id2`=?,`change_airport_id`=?,`user`=?,`desc`=?,`date_time`=? where id=?");
            ChangeAirportLogDaoImpl.setPreparedStatementValues(ps, changeAirportLog);
            ps.setInt(7, changeAirportLog.getId());
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:UPDATE change_airport_log[id=" + changeAirportLog.getId() + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int deleteById(Integer id) throws DaoException {
		 try {
		 	Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("delete from change_airport_log where id=?");
            ps.setInt(1, id);
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:DELETE change_airport_log[id=" + id + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}

	
		
	private static String buildClause(ChangeAirportLogExample changeAirportLogExample) {
		StringBuilder builder = new StringBuilder();
		boolean firstO = true;
		for (ChangeAirportLogExample.Criteria criteria : changeAirportLogExample.getOredCriteria()) {
			if (firstO) {
				firstO = false;
			} else {
				builder.append(" or ");
			}
			
			if (criteria.isValid()) {
				builder.append('(');
				boolean first = true;
				for (ChangeAirportLogExample.Criterion criterion : criteria.getAllCriteria()) {
					if (first) {
						first = false;
					} else {
						builder.append(" and ");
					}
					
					if (criterion.isNoValue()) {
						builder.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isBetweenValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
						
						builder.append(" and ");
						builder.append("'");
						if (criterion.getSecondValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getSecondValue()));
						} else {
							builder.append(criterion.getSecondValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isListValue()) {
						builder.append(criterion.getCondition());
						builder.append('(');
						List<?> items = (List<?>) criterion.getValue();
						boolean firstC = true;
						for (Object item : items) {
							if (firstC) {
								firstC = false;
							} else {
								builder.append(", ");
							}
							builder.append("'");
							if (item instanceof java.util.Date) {
								builder.append(dateFormat.format(item));
							} else {
								builder.append(item.toString().replace("'", "\'"));
							}
							builder.append("'");
						}
						builder.append(')');
					}
				}
				builder.append(')');
			}
		}
		
		String clause = firstO ? "" : " where " + builder.toString();
		
		if (changeAirportLogExample.getOrderByClause() != null && !changeAirportLogExample.getOrderByClause().isEmpty()) {
			clause += " order by " + changeAirportLogExample.getOrderByClause();
		}
		
		return clause;
	}
	
	@Override
	public int countByChangeAirportLogExample(ChangeAirportLogExample changeAirportLogExample) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();

			String clause = ChangeAirportLogDaoImpl.buildClause(changeAirportLogExample);			
            ResultSet rs = stmt.executeQuery("select" + (changeAirportLogExample.isDistinct() ? " distinct " : " ") + "count(*) from change_airport_log" + clause);
            int count = -1;
            if (rs.next()) {
            	count = rs.getInt(1);
           	}
            rs.close();
            stmt.close();
            
            logger.debug("DB:COUNT change_airport_log[distinct=" + changeAirportLogExample.isDistinct() + ",clause=" + clause + "] => " + count);

            return count;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public ChangeAirportLog findByChangeAirportLogExample(ChangeAirportLogExample changeAirportLogExample) throws DaoException {
		List<ChangeAirportLog> res = this.findAllByChangeAirportLogExample(changeAirportLogExample, 0, 1);
		if (res.size() > 0) {
			return res.get(0);
		} else {
			return null;
		}
	}
	
	@Override
    public List<ChangeAirportLog> findAllByChangeAirportLogExample(ChangeAirportLogExample changeAirportLogExample) throws DaoException {
    	return this.findAllByChangeAirportLogExample(changeAirportLogExample, 0, 2000);
    }
    
    @Override
    public List<ChangeAirportLog> findAllByChangeAirportLogExample(ChangeAirportLogExample changeAirportLogExample, int limit) throws DaoException {
    	return this.findAllByChangeAirportLogExample(changeAirportLogExample, 0, limit);
    }
    
    @Override
    public List<ChangeAirportLog> findAllByChangeAirportLogExample(ChangeAirportLogExample changeAirportLogExample, int offset, int limit) throws DaoException {
    	try {
    		Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();
            String clause = ChangeAirportLogDaoImpl.buildClause(changeAirportLogExample) + " limit " + offset + "," + limit;
            
            logger.debug("DB:FIND change_airport_log[distinct=" + changeAirportLogExample.isDistinct() + ",clause=" + clause + "]");
            
            ResultSet rs = stmt.executeQuery("select" + (changeAirportLogExample.isDistinct() ? " distinct " : " ") + "`id`,`id2`,`change_airport_id`,`user`,`desc`,`date_time` from change_airport_log" + clause);

            List<ChangeAirportLog> list = new ArrayList<ChangeAirportLog>();
            while (rs.next()) {
                list.add(ChangeAirportLogDaoImpl.createInstanceFromResultSet(rs));
            }
            rs.close();
            stmt.close();

            return list;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}

}
