package com.tti.accscms.mapper.movement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.datasource.DataSourceUtils;

import com.tti.accscms.dao.DaoException;
import com.tti.accscms.dao.movement.ShipmentMovementStatusDao;

import com.tti.accscms.domain.movement.ShipmentMovementStatus;
import com.tti.accscms.domain.movement.ShipmentMovementStatusExample;

/**
 * This class was generated by Generator.
 * This class corresponds to the database table shp_movement_status
 */
public class ShipmentMovementStatusDaoImpl implements ShipmentMovementStatusDao {

	private static final Logger logger = LoggerFactory.getLogger(ShipmentMovementStatusDaoImpl.class);
	
	private static final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	
    private DataSource dataSource;
    
    public void setDataSource(DataSource dataSource) {
    	this.dataSource = dataSource;
    }
		
	private static void setPreparedStatementValues(PreparedStatement ps, ShipmentMovementStatus shipmentMovementStatus) throws SQLException {
		
		if (shipmentMovementStatus.getId() != null) {
			ps.setInt(1, shipmentMovementStatus.getId());
		} else {
			ps.setNull(1, java.sql.Types.INTEGER);
		}

		if (shipmentMovementStatus.getId2() != null) {
			ps.setInt(2, shipmentMovementStatus.getId2());
		} else {
			ps.setNull(2, java.sql.Types.INTEGER);
		}

		if (shipmentMovementStatus.getRequestNo() != null) {
			ps.setString(3, shipmentMovementStatus.getRequestNo());
		} else {
			ps.setNull(3, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getDeclarationNo() != null) {
			ps.setString(4, shipmentMovementStatus.getDeclarationNo());
		} else {
			ps.setNull(4, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getTransactionNo() != null) {
			ps.setString(5, shipmentMovementStatus.getTransactionNo());
		} else {
			ps.setNull(5, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getMawb() != null) {
			ps.setString(6, shipmentMovementStatus.getMawb());
		} else {
			ps.setNull(6, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getHawb() != null) {
			ps.setString(7, shipmentMovementStatus.getHawb());
		} else {
			ps.setNull(7, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getFlightNo() != null) {
			ps.setString(8, shipmentMovementStatus.getFlightNo());
		} else {
			ps.setNull(8, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getFlightDate() != null) {
			ps.setTimestamp(9, new java.sql.Timestamp(shipmentMovementStatus.getFlightDate().getTime()));
		} else {
			ps.setNull(9, java.sql.Types.DATE);
		}

		if (shipmentMovementStatus.getStatus() != null) {
			ps.setString(10, shipmentMovementStatus.getStatus());
		} else {
			ps.setNull(10, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getRemark() != null) {
			ps.setString(11, shipmentMovementStatus.getRemark());
		} else {
			ps.setNull(11, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getStatusDateTime() != null) {
			ps.setTimestamp(12, new java.sql.Timestamp(shipmentMovementStatus.getStatusDateTime().getTime()));
		} else {
			ps.setNull(12, java.sql.Types.TIMESTAMP);
		}

		if (shipmentMovementStatus.getNumberOfPackage() != null) {
			ps.setInt(13, shipmentMovementStatus.getNumberOfPackage());
		} else {
			ps.setNull(13, java.sql.Types.INTEGER);
		}

		if (shipmentMovementStatus.getNumberOfPackageUnit() != null) {
			ps.setString(14, shipmentMovementStatus.getNumberOfPackageUnit());
		} else {
			ps.setNull(14, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getGrossWeight() != null) {
			ps.setDouble(15, shipmentMovementStatus.getGrossWeight());
		} else {
			ps.setNull(15, java.sql.Types.DOUBLE);
		}

		if (shipmentMovementStatus.getGrossWeightUnit() != null) {
			ps.setString(16, shipmentMovementStatus.getGrossWeightUnit());
		} else {
			ps.setNull(16, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getRegistrationId() != null) {
			ps.setString(17, shipmentMovementStatus.getRegistrationId());
		} else {
			ps.setNull(17, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getGroupDeclaration() != null) {
			ps.setInt(18, shipmentMovementStatus.getGroupDeclaration());
		} else {
			ps.setNull(18, java.sql.Types.INTEGER);
		}

		if (shipmentMovementStatus.getUser() != null) {
			ps.setString(19, shipmentMovementStatus.getUser());
		} else {
			ps.setNull(19, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getType() != null) {
			ps.setInt(20, shipmentMovementStatus.getType());
		} else {
			ps.setNull(20, java.sql.Types.INTEGER);
		}

		if (shipmentMovementStatus.getNetWeight() != null) {
			ps.setDouble(21, shipmentMovementStatus.getNetWeight());
		} else {
			ps.setNull(21, java.sql.Types.DOUBLE);
		}

		if (shipmentMovementStatus.getQuantity() != null) {
			ps.setInt(22, shipmentMovementStatus.getQuantity());
		} else {
			ps.setNull(22, java.sql.Types.INTEGER);
		}

		if (shipmentMovementStatus.getNetWeightUnit() != null) {
			ps.setString(23, shipmentMovementStatus.getNetWeightUnit());
		} else {
			ps.setNull(23, java.sql.Types.VARCHAR);
		}

		if (shipmentMovementStatus.getQuantityUnit() != null) {
			ps.setString(24, shipmentMovementStatus.getQuantityUnit());
		} else {
			ps.setNull(24, java.sql.Types.VARCHAR);
		}

	}

		
	private static ShipmentMovementStatus createInstanceFromResultSet(ResultSet rs) throws SQLException {
		ShipmentMovementStatus shipmentMovementStatus = new ShipmentMovementStatus();
		
		Integer col1 = rs.getInt("id");
		shipmentMovementStatus.setId(rs.wasNull() ? null : col1);

		Integer col2 = rs.getInt("id2");
		shipmentMovementStatus.setId2(rs.wasNull() ? null : col2);

		String col3 = rs.getString("request_no");
		shipmentMovementStatus.setRequestNo(rs.wasNull() ? null : col3);

		String col4 = rs.getString("declaration_no");
		shipmentMovementStatus.setDeclarationNo(rs.wasNull() ? null : col4);

		String col5 = rs.getString("transaction_no");
		shipmentMovementStatus.setTransactionNo(rs.wasNull() ? null : col5);

		String col6 = rs.getString("mawb");
		shipmentMovementStatus.setMawb(rs.wasNull() ? null : col6);

		String col7 = rs.getString("hawb");
		shipmentMovementStatus.setHawb(rs.wasNull() ? null : col7);

		String col8 = rs.getString("flight_no");
		shipmentMovementStatus.setFlightNo(rs.wasNull() ? null : col8);

		java.sql.Timestamp col9 = rs.getTimestamp("flight_date");
		shipmentMovementStatus.setFlightDate(rs.wasNull() ? null : new java.util.Date(col9.getTime()));

		String col10 = rs.getString("status");
		shipmentMovementStatus.setStatus(rs.wasNull() ? null : col10);

		String col11 = rs.getString("remark");
		shipmentMovementStatus.setRemark(rs.wasNull() ? null : col11);

		java.sql.Timestamp col12 = rs.getTimestamp("status_date_time");
		shipmentMovementStatus.setStatusDateTime(rs.wasNull() ? null : new java.util.Date(col12.getTime()));

		Integer col13 = rs.getInt("number_of_package");
		shipmentMovementStatus.setNumberOfPackage(rs.wasNull() ? null : col13);

		String col14 = rs.getString("number_of_package_unit");
		shipmentMovementStatus.setNumberOfPackageUnit(rs.wasNull() ? null : col14);

		Double col15 = rs.getDouble("gross_weight");
		shipmentMovementStatus.setGrossWeight(rs.wasNull() ? null : col15);

		String col16 = rs.getString("gross_weight_unit");
		shipmentMovementStatus.setGrossWeightUnit(rs.wasNull() ? null : col16);

		String col17 = rs.getString("registration_id");
		shipmentMovementStatus.setRegistrationId(rs.wasNull() ? null : col17);

		Integer col18 = rs.getInt("group_declaration");
		shipmentMovementStatus.setGroupDeclaration(rs.wasNull() ? null : col18);

		String col19 = rs.getString("user");
		shipmentMovementStatus.setUser(rs.wasNull() ? null : col19);

		Integer col20 = rs.getInt("type");
		shipmentMovementStatus.setType(rs.wasNull() ? null : col20);

		Double col21 = rs.getDouble("net_weight");
		shipmentMovementStatus.setNetWeight(rs.wasNull() ? null : col21);

		Integer col22 = rs.getInt("quantity");
		shipmentMovementStatus.setQuantity(rs.wasNull() ? null : col22);

		String col23 = rs.getString("net_weight_unit");
		shipmentMovementStatus.setNetWeightUnit(rs.wasNull() ? null : col23);

		String col24 = rs.getString("quantity_unit");
		shipmentMovementStatus.setQuantityUnit(rs.wasNull() ? null : col24);


		return shipmentMovementStatus;
	}  

		
	@Override
	public int insert(ShipmentMovementStatus shipmentMovementStatus) throws DaoException {
		if (shipmentMovementStatus == null) {
			throw new DaoException("Cannot insert shp_movement_status with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("insert into shp_movement_status(`id`,`id2`,`request_no`,`declaration_no`,`transaction_no`,`mawb`,`hawb`,`flight_no`,`flight_date`,`status`,`remark`,`status_date_time`,`number_of_package`,`number_of_package_unit`,`gross_weight`,`gross_weight_unit`,`registration_id`,`group_declaration`,`user`,`type`,`net_weight`,`quantity`,`net_weight_unit`,`quantity_unit`) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            ShipmentMovementStatusDaoImpl.setPreparedStatementValues(ps, shipmentMovementStatus);
			ps.setNull(1, java.sql.Types.INTEGER);
            ps.execute();
			int id = -1;
			ResultSet rs = ps.getGeneratedKeys();
			if (rs.next()) {
				id = rs.getInt(1);
			}
			rs.close();
			ps.close();

			logger.info("DB:INSERT shp_movement_status[id=" + id + "]");

			return id;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int count() throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
			Statement stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select count(*) from shp_movement_status");
			
			int count = -1;
			if (rs.next()) { 
				count = rs.getInt(1);
			}
			rs.close();
			stmt.close();
			
			logger.debug("DB:COUNT shp_movement_status => " + count);
			
			return count;
		} catch (SQLException e) {
			throw new DaoException(e);
		}
	}

	@Override
	public ShipmentMovementStatus findById(Integer id) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("select `id`,`id2`,`request_no`,`declaration_no`,`transaction_no`,`mawb`,`hawb`,`flight_no`,`flight_date`,`status`,`remark`,`status_date_time`,`number_of_package`,`number_of_package_unit`,`gross_weight`,`gross_weight_unit`,`registration_id`,`group_declaration`,`user`,`type`,`net_weight`,`quantity`,`net_weight_unit`,`quantity_unit` from shp_movement_status where id=?");
            ps.setInt(1, id);
            
            logger.debug("DB:FIND shp_movement_status[id=" + id + "]");

            ResultSet rs = ps.executeQuery();
            ShipmentMovementStatus instance = null;
            if (rs.next()) {
                instance = ShipmentMovementStatusDaoImpl.createInstanceFromResultSet(rs);
            }
            rs.close();
            ps.close();

            return instance;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int update(ShipmentMovementStatus shipmentMovementStatus) throws DaoException {
		if (shipmentMovementStatus == null) {
			throw new DaoException("Cannot insert shp_movement_status with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("update shp_movement_status set `id`=?,`id2`=?,`request_no`=?,`declaration_no`=?,`transaction_no`=?,`mawb`=?,`hawb`=?,`flight_no`=?,`flight_date`=?,`status`=?,`remark`=?,`status_date_time`=?,`number_of_package`=?,`number_of_package_unit`=?,`gross_weight`=?,`gross_weight_unit`=?,`registration_id`=?,`group_declaration`=?,`user`=?,`type`=?,`net_weight`=?,`quantity`=?,`net_weight_unit`=?,`quantity_unit`=? where id=?");
            ShipmentMovementStatusDaoImpl.setPreparedStatementValues(ps, shipmentMovementStatus);
            ps.setInt(25, shipmentMovementStatus.getId());
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:UPDATE shp_movement_status[id=" + shipmentMovementStatus.getId() + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int deleteById(Integer id) throws DaoException {
		 try {
		 	Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("delete from shp_movement_status where id=?");
            ps.setInt(1, id);
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:DELETE shp_movement_status[id=" + id + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}

	
		
	private static String buildClause(ShipmentMovementStatusExample shipmentMovementStatusExample) {
		StringBuilder builder = new StringBuilder();
		boolean firstO = true;
		for (ShipmentMovementStatusExample.Criteria criteria : shipmentMovementStatusExample.getOredCriteria()) {
			if (firstO) {
				firstO = false;
			} else {
				builder.append(" or ");
			}
			
			if (criteria.isValid()) {
				builder.append('(');
				boolean first = true;
				for (ShipmentMovementStatusExample.Criterion criterion : criteria.getAllCriteria()) {
					if (first) {
						first = false;
					} else {
						builder.append(" and ");
					}
					
					if (criterion.isNoValue()) {
						builder.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isBetweenValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
						
						builder.append(" and ");
						builder.append("'");
						if (criterion.getSecondValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getSecondValue()));
						} else {
							builder.append(criterion.getSecondValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isListValue()) {
						builder.append(criterion.getCondition());
						builder.append('(');
						List<?> items = (List<?>) criterion.getValue();
						boolean firstC = true;
						for (Object item : items) {
							if (firstC) {
								firstC = false;
							} else {
								builder.append(", ");
							}
							builder.append("'");
							if (item instanceof java.util.Date) {
								builder.append(dateFormat.format(item));
							} else {
								builder.append(item.toString().replace("'", "\'"));
							}
							builder.append("'");
						}
						builder.append(')');
					}
				}
				builder.append(')');
			}
		}
		
		String clause = firstO ? "" : " where " + builder.toString();
		
		if (shipmentMovementStatusExample.getOrderByClause() != null && !shipmentMovementStatusExample.getOrderByClause().isEmpty()) {
			clause += " order by " + shipmentMovementStatusExample.getOrderByClause();
		}
		
		return clause;
	}
	
	@Override
	public int countByShipmentMovementStatusExample(ShipmentMovementStatusExample shipmentMovementStatusExample) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();

			String clause = ShipmentMovementStatusDaoImpl.buildClause(shipmentMovementStatusExample);			
            ResultSet rs = stmt.executeQuery("select" + (shipmentMovementStatusExample.isDistinct() ? " distinct " : " ") + "count(*) from shp_movement_status" + clause);
            int count = -1;
            if (rs.next()) {
            	count = rs.getInt(1);
           	}
            rs.close();
            stmt.close();
            
            logger.debug("DB:COUNT shp_movement_status[distinct=" + shipmentMovementStatusExample.isDistinct() + ",clause=" + clause + "] => " + count);

            return count;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public ShipmentMovementStatus findByShipmentMovementStatusExample(ShipmentMovementStatusExample shipmentMovementStatusExample) throws DaoException {
		List<ShipmentMovementStatus> res = this.findAllByShipmentMovementStatusExample(shipmentMovementStatusExample, 0, 1);
		if (res.size() > 0) {
			return res.get(0);
		} else {
			return null;
		}
	}
	
	@Override
    public List<ShipmentMovementStatus> findAllByShipmentMovementStatusExample(ShipmentMovementStatusExample shipmentMovementStatusExample) throws DaoException {
    	return this.findAllByShipmentMovementStatusExample(shipmentMovementStatusExample, 0, 2000);
    }
    
    @Override
    public List<ShipmentMovementStatus> findAllByShipmentMovementStatusExample(ShipmentMovementStatusExample shipmentMovementStatusExample, int limit) throws DaoException {
    	return this.findAllByShipmentMovementStatusExample(shipmentMovementStatusExample, 0, limit);
    }
    
    @Override
    public List<ShipmentMovementStatus> findAllByShipmentMovementStatusExample(ShipmentMovementStatusExample shipmentMovementStatusExample, int offset, int limit) throws DaoException {
    	try {
    		Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();
            String clause = ShipmentMovementStatusDaoImpl.buildClause(shipmentMovementStatusExample) + " limit " + offset + "," + limit;
            
            logger.debug("DB:FIND shp_movement_status[distinct=" + shipmentMovementStatusExample.isDistinct() + ",clause=" + clause + "]");
            
            ResultSet rs = stmt.executeQuery("select" + (shipmentMovementStatusExample.isDistinct() ? " distinct " : " ") + "`id`,`id2`,`request_no`,`declaration_no`,`transaction_no`,`mawb`,`hawb`,`flight_no`,`flight_date`,`status`,`remark`,`status_date_time`,`number_of_package`,`number_of_package_unit`,`gross_weight`,`gross_weight_unit`,`registration_id`,`group_declaration`,`user`,`type`,`net_weight`,`quantity`,`net_weight_unit`,`quantity_unit` from shp_movement_status" + clause);

            List<ShipmentMovementStatus> list = new ArrayList<ShipmentMovementStatus>();
            while (rs.next()) {
                list.add(ShipmentMovementStatusDaoImpl.createInstanceFromResultSet(rs));
            }
            rs.close();
            stmt.close();

            return list;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}

}
