package com.tti.accscms.mapper.clientmanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.datasource.DataSourceUtils;

import com.tti.accscms.dao.DaoException;
import com.tti.accscms.dao.clientmanagement.RequestLogDao;

import com.tti.accscms.domain.clientmanagement.RequestLog;
import com.tti.accscms.domain.clientmanagement.RequestLogExample;

/**
 * This class was generated by Generator.
 * This class corresponds to the database table request_log
 */
public class RequestLogDaoImpl implements RequestLogDao {

	private static final Logger logger = LoggerFactory.getLogger(RequestLogDaoImpl.class);
	
	private static final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	
    private DataSource dataSource;
    
    public void setDataSource(DataSource dataSource) {
    	this.dataSource = dataSource;
    }
		
	private static void setPreparedStatementValues(PreparedStatement ps, RequestLog requestLog) throws SQLException {
		
		if (requestLog.getId() != null) {
			ps.setLong(1, requestLog.getId());
		} else {
			ps.setNull(1, java.sql.Types.BIGINT);
		}

		if (requestLog.getId2() != null) {
			ps.setInt(2, requestLog.getId2());
		} else {
			ps.setNull(2, java.sql.Types.INTEGER);
		}

		if (requestLog.getUsername() != null) {
			ps.setString(3, requestLog.getUsername());
		} else {
			ps.setNull(3, java.sql.Types.VARCHAR);
		}

		if (requestLog.getNonce() != null) {
			ps.setString(4, requestLog.getNonce());
		} else {
			ps.setNull(4, java.sql.Types.VARCHAR);
		}

		if (requestLog.getCreateDateTime() != null) {
			ps.setTimestamp(5, new java.sql.Timestamp(requestLog.getCreateDateTime().getTime()));
		} else {
			ps.setNull(5, java.sql.Types.TIMESTAMP);
		}

	}

		
	private static RequestLog createInstanceFromResultSet(ResultSet rs) throws SQLException {
		RequestLog requestLog = new RequestLog();
		
		Long col1 = rs.getLong("id");
		requestLog.setId(rs.wasNull() ? null : col1);

		Integer col2 = rs.getInt("id2");
		requestLog.setId2(rs.wasNull() ? null : col2);

		String col3 = rs.getString("username");
		requestLog.setUsername(rs.wasNull() ? null : col3);

		String col4 = rs.getString("nonce");
		requestLog.setNonce(rs.wasNull() ? null : col4);

		java.sql.Timestamp col5 = rs.getTimestamp("create_date_time");
		requestLog.setCreateDateTime(rs.wasNull() ? null : new java.util.Date(col5.getTime()));


		return requestLog;
	}  

		
	@Override
	public long insert(RequestLog requestLog) throws DaoException {
		if (requestLog == null) {
			throw new DaoException("Cannot insert request_log with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("insert into request_log(`id`,`id2`,`username`,`nonce`,`create_date_time`) values(?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            RequestLogDaoImpl.setPreparedStatementValues(ps, requestLog);
			ps.setNull(1, java.sql.Types.BIGINT);
            ps.execute();
			long id = -1;
			ResultSet rs = ps.getGeneratedKeys();
			if (rs.next()) {
				id = rs.getLong(1);
			}
			rs.close();
			ps.close();

			logger.info("DB:INSERT request_log[id=" + id + "]");

			return id;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public long count() throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
			Statement stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select count(*) from request_log");
			
			long count = -1;
			if (rs.next()) { 
				count = rs.getLong(1);
			}
			rs.close();
			stmt.close();
			
			logger.debug("DB:COUNT request_log => " + count);
			
			return count;
		} catch (SQLException e) {
			throw new DaoException(e);
		}
	}

	@Override
	public RequestLog findById(Long id) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("select `id`,`id2`,`username`,`nonce`,`create_date_time` from request_log where id=?");
            ps.setLong(1, id);
            
            logger.debug("DB:FIND request_log[id=" + id + "]");

            ResultSet rs = ps.executeQuery();
            RequestLog instance = null;
            if (rs.next()) {
                instance = RequestLogDaoImpl.createInstanceFromResultSet(rs);
            }
            rs.close();
            ps.close();

            return instance;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int update(RequestLog requestLog) throws DaoException {
		if (requestLog == null) {
			throw new DaoException("Cannot insert request_log with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("update request_log set `id`=?,`id2`=?,`username`=?,`nonce`=?,`create_date_time`=? where id=?");
            RequestLogDaoImpl.setPreparedStatementValues(ps, requestLog);
            ps.setLong(6, requestLog.getId());
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:UPDATE request_log[id=" + requestLog.getId() + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int deleteById(Long id) throws DaoException {
		 try {
		 	Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("delete from request_log where id=?");
            ps.setLong(1, id);
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:DELETE request_log[id=" + id + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}

	
		
	private static String buildClause(RequestLogExample requestLogExample) {
		StringBuilder builder = new StringBuilder();
		boolean firstO = true;
		for (RequestLogExample.Criteria criteria : requestLogExample.getOredCriteria()) {
			if (firstO) {
				firstO = false;
			} else {
				builder.append(" or ");
			}
			
			if (criteria.isValid()) {
				builder.append('(');
				boolean first = true;
				for (RequestLogExample.Criterion criterion : criteria.getAllCriteria()) {
					if (first) {
						first = false;
					} else {
						builder.append(" and ");
					}
					
					if (criterion.isNoValue()) {
						builder.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isBetweenValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
						
						builder.append(" and ");
						builder.append("'");
						if (criterion.getSecondValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getSecondValue()));
						} else {
							builder.append(criterion.getSecondValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isListValue()) {
						builder.append(criterion.getCondition());
						builder.append('(');
						List<?> items = (List<?>) criterion.getValue();
						boolean firstC = true;
						for (Object item : items) {
							if (firstC) {
								firstC = false;
							} else {
								builder.append(", ");
							}
							builder.append("'");
							if (item instanceof java.util.Date) {
								builder.append(dateFormat.format(item));
							} else {
								builder.append(item.toString().replace("'", "\'"));
							}
							builder.append("'");
						}
						builder.append(')');
					}
				}
				builder.append(')');
			}
		}
		
		String clause = firstO ? "" : " where " + builder.toString();
		
		if (requestLogExample.getOrderByClause() != null && !requestLogExample.getOrderByClause().isEmpty()) {
			clause += " order by " + requestLogExample.getOrderByClause();
		}
		
		return clause;
	}
	
	@Override
	public long countByRequestLogExample(RequestLogExample requestLogExample) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();

			String clause = RequestLogDaoImpl.buildClause(requestLogExample);			
            ResultSet rs = stmt.executeQuery("select" + (requestLogExample.isDistinct() ? " distinct " : " ") + "count(*) from request_log" + clause);
            long count = -1;
            if (rs.next()) {
            	count = rs.getLong(1);
           	}
            rs.close();
            stmt.close();
            
            logger.debug("DB:COUNT request_log[distinct=" + requestLogExample.isDistinct() + ",clause=" + clause + "] => " + count);

            return count;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public RequestLog findByRequestLogExample(RequestLogExample requestLogExample) throws DaoException {
		List<RequestLog> res = this.findAllByRequestLogExample(requestLogExample, 0, 1);
		if (res.size() > 0) {
			return res.get(0);
		} else {
			return null;
		}
	}
	
	@Override
    public List<RequestLog> findAllByRequestLogExample(RequestLogExample requestLogExample) throws DaoException {
    	return this.findAllByRequestLogExample(requestLogExample, 0, 2000);
    }
    
    @Override
    public List<RequestLog> findAllByRequestLogExample(RequestLogExample requestLogExample, int limit) throws DaoException {
    	return this.findAllByRequestLogExample(requestLogExample, 0, limit);
    }
    
    @Override
    public List<RequestLog> findAllByRequestLogExample(RequestLogExample requestLogExample, int offset, int limit) throws DaoException {
    	try {
    		Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();
            String clause = RequestLogDaoImpl.buildClause(requestLogExample) + " limit " + offset + "," + limit;
            
            logger.debug("DB:FIND request_log[distinct=" + requestLogExample.isDistinct() + ",clause=" + clause + "]");
            
            ResultSet rs = stmt.executeQuery("select" + (requestLogExample.isDistinct() ? " distinct " : " ") + "`id`,`id2`,`username`,`nonce`,`create_date_time` from request_log" + clause);

            List<RequestLog> list = new ArrayList<RequestLog>();
            while (rs.next()) {
                list.add(RequestLogDaoImpl.createInstanceFromResultSet(rs));
            }
            rs.close();
            stmt.close();

            return list;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}

}
