package com.tti.accscms.mapper.clientmanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.datasource.DataSourceUtils;

import com.tti.accscms.dao.DaoException;
import com.tti.accscms.dao.clientmanagement.ShedNoDao;

import com.tti.accscms.domain.clientmanagement.ShedNo;
import com.tti.accscms.domain.clientmanagement.ShedNoExample;
import com.tti.accscms.domain.clientmanagement.UserCompany;

/**
 * This class was generated by Generator.
 * This class corresponds to the database table shed_no
 */
public class ShedNoDaoImpl implements ShedNoDao {

	private static final Logger logger = LoggerFactory.getLogger(ShedNoDaoImpl.class);
	
	private static final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	
    private DataSource dataSource;
    
    public void setDataSource(DataSource dataSource) {
    	this.dataSource = dataSource;
    }
		
	private static void setPreparedStatementValues(PreparedStatement ps, ShedNo shedNo) throws SQLException {
		
		if (shedNo.getId() != null) {
			ps.setInt(1, shedNo.getId());
		} else {
			ps.setNull(1, java.sql.Types.INTEGER);
		}

		if (shedNo.getId2() != null) {
			ps.setInt(2, shedNo.getId2());
		} else {
			ps.setNull(2, java.sql.Types.INTEGER);
		}

		if (shedNo.getCompanyId() != null) {
			ps.setInt(3, shedNo.getCompanyId());
		} else {
			ps.setNull(3, java.sql.Types.INTEGER);
		}

		if (shedNo.getShedNo() != null) {
			ps.setString(4, shedNo.getShedNo());
		} else {
			ps.setNull(4, java.sql.Types.VARCHAR);
		}

		if (shedNo.getType() != null) {
			ps.setString(5, shedNo.getType());
		} else {
			ps.setNull(5, java.sql.Types.VARCHAR);
		}

		if (shedNo.getModifiedDate() != null) {
			ps.setTimestamp(6, new java.sql.Timestamp(shedNo.getModifiedDate().getTime()));
		} else {
			ps.setTimestamp(6, new java.sql.Timestamp(System.currentTimeMillis()));
		}

	}

		
	private static ShedNo createInstanceFromResultSet(ResultSet rs) throws SQLException {
		ShedNo shedNo = new ShedNo();
		
		Integer col1 = rs.getInt("id");
		shedNo.setId(rs.wasNull() ? null : col1);

		Integer col2 = rs.getInt("id2");
		shedNo.setId2(rs.wasNull() ? null : col2);

		Integer col3 = rs.getInt("company_id");
		shedNo.setCompanyId(rs.wasNull() ? null : col3);

		String col4 = rs.getString("shed_no");
		shedNo.setShedNo(rs.wasNull() ? null : col4);

		String col5 = rs.getString("type");
		shedNo.setType(rs.wasNull() ? null : col5);

		java.sql.Timestamp col6 = rs.getTimestamp("modified_date");
		shedNo.setModifiedDate(rs.wasNull() ? null : new java.util.Date(col6.getTime()));


		return shedNo;
	}  

		
	@Override
	public int insert(ShedNo shedNo) throws DaoException {
		if (shedNo == null) {
			throw new DaoException("Cannot insert shed_no with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("insert into shed_no(`id`,`id2`,`company_id`,`shed_no`,`type`,`modified_date`) values(?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            ShedNoDaoImpl.setPreparedStatementValues(ps, shedNo);
			ps.setNull(1, java.sql.Types.INTEGER);
            ps.execute();
			int id = -1;
			ResultSet rs = ps.getGeneratedKeys();
			if (rs.next()) {
				id = rs.getInt(1);
			}
			rs.close();
			ps.close();

			logger.info("DB:INSERT shed_no[id=" + id + "]");

			return id;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int count() throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
			Statement stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select count(*) from shed_no");
			
			int count = -1;
			if (rs.next()) { 
				count = rs.getInt(1);
			}
			rs.close();
			stmt.close();
			
			logger.debug("DB:COUNT shed_no => " + count);
			
			return count;
		} catch (SQLException e) {
			throw new DaoException(e);
		}
	}

	@Override
	public ShedNo findById(Integer id) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("select `id`,`id2`,`company_id`,`shed_no`,`type`,`modified_date` from shed_no where id=?");
            ps.setInt(1, id);
            
            logger.debug("DB:FIND shed_no[id=" + id + "]");

            ResultSet rs = ps.executeQuery();
            ShedNo instance = null;
            if (rs.next()) {
                instance = ShedNoDaoImpl.createInstanceFromResultSet(rs);
            }
            rs.close();
            ps.close();

            return instance;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int update(ShedNo shedNo) throws DaoException {
		if (shedNo == null) {
			throw new DaoException("Cannot insert shed_no with null value.");
		}
		
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("update shed_no set `id`=?,`id2`=?,`company_id`=?,`shed_no`=?,`type`=?,`modified_date`=? where id=?");
            ShedNoDaoImpl.setPreparedStatementValues(ps, shedNo);
            ps.setInt(7, shedNo.getId());
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:UPDATE shed_no[id=" + shedNo.getId() + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public int deleteById(Integer id) throws DaoException {
		 try {
		 	Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = conn.prepareStatement("delete from shed_no where id=?");
            ps.setInt(1, id);
            int count = ps.executeUpdate();
            ps.close();
            
            logger.info("DB:DELETE shed_no[id=" + id + "] => " + count);

            return count;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}

	
	@Override
	public List<ShedNo> findAllByUserCompany(UserCompany userCompany) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            PreparedStatement ps = null;
            if (userCompany == null || userCompany.getId() == null) {
            	ps = conn.prepareStatement("select `id`,`id2`,`company_id`,`shed_no`,`type`,`modified_date` from shed_no where company_id=null");
            } else {
            	ps = conn.prepareStatement("select `id`,`id2`,`company_id`,`shed_no`,`type`,`modified_date` from shed_no where company_id=?");
            	ps.setInt(1, userCompany.getId());
            }
            
            logger.debug("DB:FIND shed_no[company_id=" + (userCompany != null ? userCompany.getId() : "null") + "]");
            
            ResultSet rs = ps.executeQuery();

            List<ShedNo> list = new ArrayList<ShedNo>();
            while (rs.next()) {
                list.add(ShedNoDaoImpl.createInstanceFromResultSet(rs));
            }
            rs.close();
            ps.close();

            return list;
        } catch (SQLException e) {
            throw new DaoException(e);
        }
	}

		
	private static String buildClause(ShedNoExample shedNoExample) {
		StringBuilder builder = new StringBuilder();
		boolean firstO = true;
		for (ShedNoExample.Criteria criteria : shedNoExample.getOredCriteria()) {
			if (firstO) {
				firstO = false;
			} else {
				builder.append(" or ");
			}
			
			if (criteria.isValid()) {
				builder.append('(');
				boolean first = true;
				for (ShedNoExample.Criterion criterion : criteria.getAllCriteria()) {
					if (first) {
						first = false;
					} else {
						builder.append(" and ");
					}
					
					if (criterion.isNoValue()) {
						builder.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isBetweenValue()) {
						builder.append(criterion.getCondition());
						builder.append(' ');
						
						builder.append("'");
						if (criterion.getValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getValue()));
						} else {
							builder.append(criterion.getValue().toString().replace("'", "\'"));
						}
						builder.append("'");
						
						builder.append(" and ");
						builder.append("'");
						if (criterion.getSecondValue() instanceof java.util.Date) {
							builder.append(dateFormat.format(criterion.getSecondValue()));
						} else {
							builder.append(criterion.getSecondValue().toString().replace("'", "\'"));
						}
						builder.append("'");
					} else if (criterion.isListValue()) {
						builder.append(criterion.getCondition());
						builder.append('(');
						List<?> items = (List<?>) criterion.getValue();
						boolean firstC = true;
						for (Object item : items) {
							if (firstC) {
								firstC = false;
							} else {
								builder.append(", ");
							}
							builder.append("'");
							if (item instanceof java.util.Date) {
								builder.append(dateFormat.format(item));
							} else {
								builder.append(item.toString().replace("'", "\'"));
							}
							builder.append("'");
						}
						builder.append(')');
					}
				}
				builder.append(')');
			}
		}
		
		String clause = firstO ? "" : " where " + builder.toString();
		
		if (shedNoExample.getOrderByClause() != null && !shedNoExample.getOrderByClause().isEmpty()) {
			clause += " order by " + shedNoExample.getOrderByClause();
		}
		
		return clause;
	}
	
	@Override
	public int countByShedNoExample(ShedNoExample shedNoExample) throws DaoException {
		try {
			Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();

			String clause = ShedNoDaoImpl.buildClause(shedNoExample);			
            ResultSet rs = stmt.executeQuery("select" + (shedNoExample.isDistinct() ? " distinct " : " ") + "count(*) from shed_no" + clause);
            int count = -1;
            if (rs.next()) {
            	count = rs.getInt(1);
           	}
            rs.close();
            stmt.close();
            
            logger.debug("DB:COUNT shed_no[distinct=" + shedNoExample.isDistinct() + ",clause=" + clause + "] => " + count);

            return count;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}
	
	@Override
	public ShedNo findByShedNoExample(ShedNoExample shedNoExample) throws DaoException {
		List<ShedNo> res = this.findAllByShedNoExample(shedNoExample, 0, 1);
		if (res.size() > 0) {
			return res.get(0);
		} else {
			return null;
		}
	}
	
	@Override
    public List<ShedNo> findAllByShedNoExample(ShedNoExample shedNoExample) throws DaoException {
    	return this.findAllByShedNoExample(shedNoExample, 0, 2000);
    }
    
    @Override
    public List<ShedNo> findAllByShedNoExample(ShedNoExample shedNoExample, int limit) throws DaoException {
    	return this.findAllByShedNoExample(shedNoExample, 0, limit);
    }
    
    @Override
    public List<ShedNo> findAllByShedNoExample(ShedNoExample shedNoExample, int offset, int limit) throws DaoException {
    	try {
    		Connection conn = DataSourceUtils.doGetConnection(dataSource);
            Statement stmt = conn.createStatement();
            String clause = ShedNoDaoImpl.buildClause(shedNoExample) + " limit " + offset + "," + limit;
            
            logger.debug("DB:FIND shed_no[distinct=" + shedNoExample.isDistinct() + ",clause=" + clause + "]");
            
            ResultSet rs = stmt.executeQuery("select" + (shedNoExample.isDistinct() ? " distinct " : " ") + "`id`,`id2`,`company_id`,`shed_no`,`type`,`modified_date` from shed_no" + clause);

            List<ShedNo> list = new ArrayList<ShedNo>();
            while (rs.next()) {
                list.add(ShedNoDaoImpl.createInstanceFromResultSet(rs));
            }
            rs.close();
            stmt.close();

            return list;
        } catch (Exception e) {
            throw new DaoException(e);
        }
	}

}
