package com.tti.accscms.domain.manifest;

import java.util.Date;

public class VesselScheduleControl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.id
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.id2
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Integer id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.reference_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String referenceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.received_control_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String receivedControlNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.mode_of_transport
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String modeOfTransport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.processing_indicator
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String processingIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.type_of_transport
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String typeOfTransport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.ship_agent_tax_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String shipAgentTaxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.ship_agent_branch
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Integer shipAgentBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.callsign
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String callsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.vessel_name
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String vesselName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.master_name
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String masterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.previous_flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String previousFlightNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.previous_date
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Date previousDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.nationality
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.net_register_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Double netRegisterTonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.gross_register_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Double grossRegisterTonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.dead_weight_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Double deadWeightTonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.registration_id
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private String registrationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Date modifiedDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vsed_control.type
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.id
     *
     * @return the value of vsed_control.id
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.id
     *
     * @param id the value for vsed_control.id
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.id2
     *
     * @return the value of vsed_control.id2
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.id2
     *
     * @param id2 the value for vsed_control.id2
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setId2(Integer id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.reference_number
     *
     * @return the value of vsed_control.reference_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.reference_number
     *
     * @param referenceNumber the value for vsed_control.reference_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.received_control_number
     *
     * @return the value of vsed_control.received_control_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getReceivedControlNumber() {
        return receivedControlNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.received_control_number
     *
     * @param receivedControlNumber the value for vsed_control.received_control_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setReceivedControlNumber(String receivedControlNumber) {
        this.receivedControlNumber = receivedControlNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.mode_of_transport
     *
     * @return the value of vsed_control.mode_of_transport
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getModeOfTransport() {
        return modeOfTransport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.mode_of_transport
     *
     * @param modeOfTransport the value for vsed_control.mode_of_transport
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setModeOfTransport(String modeOfTransport) {
        this.modeOfTransport = modeOfTransport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.processing_indicator
     *
     * @return the value of vsed_control.processing_indicator
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getProcessingIndicator() {
        return processingIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.processing_indicator
     *
     * @param processingIndicator the value for vsed_control.processing_indicator
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setProcessingIndicator(String processingIndicator) {
        this.processingIndicator = processingIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.type_of_transport
     *
     * @return the value of vsed_control.type_of_transport
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getTypeOfTransport() {
        return typeOfTransport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.type_of_transport
     *
     * @param typeOfTransport the value for vsed_control.type_of_transport
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setTypeOfTransport(String typeOfTransport) {
        this.typeOfTransport = typeOfTransport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.ship_agent_tax_number
     *
     * @return the value of vsed_control.ship_agent_tax_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getShipAgentTaxNumber() {
        return shipAgentTaxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.ship_agent_tax_number
     *
     * @param shipAgentTaxNumber the value for vsed_control.ship_agent_tax_number
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setShipAgentTaxNumber(String shipAgentTaxNumber) {
        this.shipAgentTaxNumber = shipAgentTaxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.ship_agent_branch
     *
     * @return the value of vsed_control.ship_agent_branch
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Integer getShipAgentBranch() {
        return shipAgentBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.ship_agent_branch
     *
     * @param shipAgentBranch the value for vsed_control.ship_agent_branch
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setShipAgentBranch(Integer shipAgentBranch) {
        this.shipAgentBranch = shipAgentBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.callsign
     *
     * @return the value of vsed_control.callsign
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getCallsign() {
        return callsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.callsign
     *
     * @param callsign the value for vsed_control.callsign
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setCallsign(String callsign) {
        this.callsign = callsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.vessel_name
     *
     * @return the value of vsed_control.vessel_name
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.vessel_name
     *
     * @param vesselName the value for vsed_control.vessel_name
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setVesselName(String vesselName) {
        this.vesselName = vesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.master_name
     *
     * @return the value of vsed_control.master_name
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getMasterName() {
        return masterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.master_name
     *
     * @param masterName the value for vsed_control.master_name
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setMasterName(String masterName) {
        this.masterName = masterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.previous_flight_no
     *
     * @return the value of vsed_control.previous_flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getPreviousFlightNo() {
        return previousFlightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.previous_flight_no
     *
     * @param previousFlightNo the value for vsed_control.previous_flight_no
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setPreviousFlightNo(String previousFlightNo) {
        this.previousFlightNo = previousFlightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.previous_date
     *
     * @return the value of vsed_control.previous_date
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Date getPreviousDate() {
        return previousDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.previous_date
     *
     * @param previousDate the value for vsed_control.previous_date
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setPreviousDate(Date previousDate) {
        this.previousDate = previousDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.nationality
     *
     * @return the value of vsed_control.nationality
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.nationality
     *
     * @param nationality the value for vsed_control.nationality
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.net_register_tonnage
     *
     * @return the value of vsed_control.net_register_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Double getNetRegisterTonnage() {
        return netRegisterTonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.net_register_tonnage
     *
     * @param netRegisterTonnage the value for vsed_control.net_register_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setNetRegisterTonnage(Double netRegisterTonnage) {
        this.netRegisterTonnage = netRegisterTonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.gross_register_tonnage
     *
     * @return the value of vsed_control.gross_register_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Double getGrossRegisterTonnage() {
        return grossRegisterTonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.gross_register_tonnage
     *
     * @param grossRegisterTonnage the value for vsed_control.gross_register_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setGrossRegisterTonnage(Double grossRegisterTonnage) {
        this.grossRegisterTonnage = grossRegisterTonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.dead_weight_tonnage
     *
     * @return the value of vsed_control.dead_weight_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Double getDeadWeightTonnage() {
        return deadWeightTonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.dead_weight_tonnage
     *
     * @param deadWeightTonnage the value for vsed_control.dead_weight_tonnage
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setDeadWeightTonnage(Double deadWeightTonnage) {
        this.deadWeightTonnage = deadWeightTonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.registration_id
     *
     * @return the value of vsed_control.registration_id
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public String getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.registration_id
     *
     * @param registrationId the value for vsed_control.registration_id
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.modified_date_time
     *
     * @return the value of vsed_control.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Date getModifiedDateTime() {
        return modifiedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.modified_date_time
     *
     * @param modifiedDateTime the value for vsed_control.modified_date_time
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setModifiedDateTime(Date modifiedDateTime) {
        this.modifiedDateTime = modifiedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vsed_control.type
     *
     * @return the value of vsed_control.type
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vsed_control.type
     *
     * @param type the value for vsed_control.type
     *
     * @mbggenerated Wed Dec 26 12:07:05 ICT 2012
     */
    public void setType(Integer type) {
        this.type = type;
    }
}