package com.tti.accscms.dao.manifest;

import java.util.List;

import com.tti.accscms.domain.manifest.AirCargoManifestDetail;
import com.tti.accscms.domain.manifest.AirCargoManifestDetailExample;
import com.tti.accscms.domain.manifest.AirCargoManifestControl;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table aman_detail
 */
public interface AirCargoManifestDetailDao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(AirCargoManifestDetail airCargoManifestDetail) throws DaoException;

    public AirCargoManifestDetail findById(Integer id) throws DaoException;
	
    public List<AirCargoManifestDetail> findAllByAirCargoManifestControl(AirCargoManifestControl airCargoManifestControl) throws DaoException;

	public int update(AirCargoManifestDetail airCargoManifestDetail) throws DaoException;
	
	public int countByAirCargoManifestDetailExample(AirCargoManifestDetailExample airCargoManifestDetailExample) throws DaoException;
	
	public AirCargoManifestDetail findByAirCargoManifestDetailExample(AirCargoManifestDetailExample airCargoManifestDetailExample) throws DaoException;
	
    public List<AirCargoManifestDetail> findAllByAirCargoManifestDetailExample(AirCargoManifestDetailExample airCargoManifestDetailExample) throws DaoException;
    
    public List<AirCargoManifestDetail> findAllByAirCargoManifestDetailExample(AirCargoManifestDetailExample airCargoManifestDetailExample, int limit) throws DaoException;
    
    public List<AirCargoManifestDetail> findAllByAirCargoManifestDetailExample(AirCargoManifestDetailExample airCargoManifestDetailExample, int offset, int limit) throws DaoException;
}
