package com.tti.accscms.dao.manifest;

import java.util.List;

import com.tti.accscms.domain.manifest.AirCargoManifestDetailHistory;
import com.tti.accscms.domain.manifest.AirCargoManifestDetailHistoryExample;
import com.tti.accscms.domain.manifest.AirCargoManifestControlHistory;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table aman_detail_his
 */
public interface AirCargoManifestDetailHistoryDao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(AirCargoManifestDetailHistory airCargoManifestDetailHistory) throws DaoException;

    public AirCargoManifestDetailHistory findById(Integer id) throws DaoException;
	
    public List<AirCargoManifestDetailHistory> findAllByAirCargoManifestControlHistory(AirCargoManifestControlHistory airCargoManifestControlHistory) throws DaoException;

	public int update(AirCargoManifestDetailHistory airCargoManifestDetailHistory) throws DaoException;
	
	public int countByAirCargoManifestDetailHistoryExample(AirCargoManifestDetailHistoryExample airCargoManifestDetailHistoryExample) throws DaoException;
	
	public AirCargoManifestDetailHistory findByAirCargoManifestDetailHistoryExample(AirCargoManifestDetailHistoryExample airCargoManifestDetailHistoryExample) throws DaoException;
	
    public List<AirCargoManifestDetailHistory> findAllByAirCargoManifestDetailHistoryExample(AirCargoManifestDetailHistoryExample airCargoManifestDetailHistoryExample) throws DaoException;
    
    public List<AirCargoManifestDetailHistory> findAllByAirCargoManifestDetailHistoryExample(AirCargoManifestDetailHistoryExample airCargoManifestDetailHistoryExample, int limit) throws DaoException;
    
    public List<AirCargoManifestDetailHistory> findAllByAirCargoManifestDetailHistoryExample(AirCargoManifestDetailHistoryExample airCargoManifestDetailHistoryExample, int offset, int limit) throws DaoException;
}
