package com.tti.accscms.dao.manifest;

import java.util.List;

import com.tti.accscms.domain.manifest.AirWaybillDetailHistory;
import com.tti.accscms.domain.manifest.AirWaybillDetailHistoryExample;
import com.tti.accscms.domain.manifest.AirWaybillControlHistory;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table abil_detail_his
 */
public interface AirWaybillDetailHistoryDao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(AirWaybillDetailHistory airWaybillDetailHistory) throws DaoException;

    public AirWaybillDetailHistory findById(Integer id) throws DaoException;
	
    public List<AirWaybillDetailHistory> findAllByAirWaybillControlHistory(AirWaybillControlHistory airWaybillControlHistory) throws DaoException;

	public int update(AirWaybillDetailHistory airWaybillDetailHistory) throws DaoException;
	
	public int countByAirWaybillDetailHistoryExample(AirWaybillDetailHistoryExample airWaybillDetailHistoryExample) throws DaoException;
	
	public AirWaybillDetailHistory findByAirWaybillDetailHistoryExample(AirWaybillDetailHistoryExample airWaybillDetailHistoryExample) throws DaoException;
	
    public List<AirWaybillDetailHistory> findAllByAirWaybillDetailHistoryExample(AirWaybillDetailHistoryExample airWaybillDetailHistoryExample) throws DaoException;
    
    public List<AirWaybillDetailHistory> findAllByAirWaybillDetailHistoryExample(AirWaybillDetailHistoryExample airWaybillDetailHistoryExample, int limit) throws DaoException;
    
    public List<AirWaybillDetailHistory> findAllByAirWaybillDetailHistoryExample(AirWaybillDetailHistoryExample airWaybillDetailHistoryExample, int offset, int limit) throws DaoException;
}
