package com.tti.accscms.dao.manifest;

import java.util.List;

import com.tti.accscms.domain.manifest.AirWaybillDetail;
import com.tti.accscms.domain.manifest.AirWaybillDetailExample;
import com.tti.accscms.domain.manifest.AirWaybillControl;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table abil_detail
 */
public interface AirWaybillDetailDao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(AirWaybillDetail airWaybillDetail) throws DaoException;

    public AirWaybillDetail findById(Integer id) throws DaoException;
	
    public List<AirWaybillDetail> findAllByAirWaybillControl(AirWaybillControl airWaybillControl) throws DaoException;

	public int update(AirWaybillDetail airWaybillDetail) throws DaoException;
	
	public int countByAirWaybillDetailExample(AirWaybillDetailExample airWaybillDetailExample) throws DaoException;
	
	public AirWaybillDetail findByAirWaybillDetailExample(AirWaybillDetailExample airWaybillDetailExample) throws DaoException;
	
    public List<AirWaybillDetail> findAllByAirWaybillDetailExample(AirWaybillDetailExample airWaybillDetailExample) throws DaoException;
    
    public List<AirWaybillDetail> findAllByAirWaybillDetailExample(AirWaybillDetailExample airWaybillDetailExample, int limit) throws DaoException;
    
    public List<AirWaybillDetail> findAllByAirWaybillDetailExample(AirWaybillDetailExample airWaybillDetailExample, int offset, int limit) throws DaoException;
}
