package com.tti.accscms.dao.manifest;

import java.util.List;

import com.tti.accscms.domain.manifest.VesselScheduleDetailHistory;
import com.tti.accscms.domain.manifest.VesselScheduleDetailHistoryExample;
import com.tti.accscms.domain.manifest.VesselScheduleControlHistory;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table vsed_detail_his
 */
public interface VesselScheduleDetailHistoryDao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(VesselScheduleDetailHistory vesselScheduleDetailHistory) throws DaoException;

    public VesselScheduleDetailHistory findById(Integer id) throws DaoException;
	
    public List<VesselScheduleDetailHistory> findAllByVesselScheduleControlHistory(VesselScheduleControlHistory vesselScheduleControlHistory) throws DaoException;

	public int update(VesselScheduleDetailHistory vesselScheduleDetailHistory) throws DaoException;
	
	public int countByVesselScheduleDetailHistoryExample(VesselScheduleDetailHistoryExample vesselScheduleDetailHistoryExample) throws DaoException;
	
	public VesselScheduleDetailHistory findByVesselScheduleDetailHistoryExample(VesselScheduleDetailHistoryExample vesselScheduleDetailHistoryExample) throws DaoException;
	
    public List<VesselScheduleDetailHistory> findAllByVesselScheduleDetailHistoryExample(VesselScheduleDetailHistoryExample vesselScheduleDetailHistoryExample) throws DaoException;
    
    public List<VesselScheduleDetailHistory> findAllByVesselScheduleDetailHistoryExample(VesselScheduleDetailHistoryExample vesselScheduleDetailHistoryExample, int limit) throws DaoException;
    
    public List<VesselScheduleDetailHistory> findAllByVesselScheduleDetailHistoryExample(VesselScheduleDetailHistoryExample vesselScheduleDetailHistoryExample, int offset, int limit) throws DaoException;
}
