package com.tti.accscms.dao.movement;

import java.util.List;

import com.tti.accscms.domain.movement.AutoBlockProfile;
import com.tti.accscms.domain.movement.AutoBlockProfileExample;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table auto_block_profile
 */
public interface AutoBlockProfileDao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(AutoBlockProfile autoBlockProfile) throws DaoException;

    public AutoBlockProfile findById(Integer id) throws DaoException;
	
	public int update(AutoBlockProfile autoBlockProfile) throws DaoException;
	
	public int countByAutoBlockProfileExample(AutoBlockProfileExample autoBlockProfileExample) throws DaoException;
	
	public AutoBlockProfile findByAutoBlockProfileExample(AutoBlockProfileExample autoBlockProfileExample) throws DaoException;
	
    public List<AutoBlockProfile> findAllByAutoBlockProfileExample(AutoBlockProfileExample autoBlockProfileExample) throws DaoException;
    
    public List<AutoBlockProfile> findAllByAutoBlockProfileExample(AutoBlockProfileExample autoBlockProfileExample, int limit) throws DaoException;
    
    public List<AutoBlockProfile> findAllByAutoBlockProfileExample(AutoBlockProfileExample autoBlockProfileExample, int offset, int limit) throws DaoException;
}
