package com.tti.accscms.dao.movement;

import java.util.List;

import com.tti.accscms.domain.movement.ExpressCustomsPermitHeader;
import com.tti.accscms.domain.movement.ExpressCustomsPermitHeaderExample;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table exp_customs_permit_header
 */
public interface ExpressCustomsPermitHeaderDao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(ExpressCustomsPermitHeader expressCustomsPermitHeader) throws DaoException;

    public ExpressCustomsPermitHeader findById(Integer id) throws DaoException;
	
	public int update(ExpressCustomsPermitHeader expressCustomsPermitHeader) throws DaoException;
	
	public int countByExpressCustomsPermitHeaderExample(ExpressCustomsPermitHeaderExample expressCustomsPermitHeaderExample) throws DaoException;
	
	public ExpressCustomsPermitHeader findByExpressCustomsPermitHeaderExample(ExpressCustomsPermitHeaderExample expressCustomsPermitHeaderExample) throws DaoException;
	
    public List<ExpressCustomsPermitHeader> findAllByExpressCustomsPermitHeaderExample(ExpressCustomsPermitHeaderExample expressCustomsPermitHeaderExample) throws DaoException;
    
    public List<ExpressCustomsPermitHeader> findAllByExpressCustomsPermitHeaderExample(ExpressCustomsPermitHeaderExample expressCustomsPermitHeaderExample, int limit) throws DaoException;
    
    public List<ExpressCustomsPermitHeader> findAllByExpressCustomsPermitHeaderExample(ExpressCustomsPermitHeaderExample expressCustomsPermitHeaderExample, int offset, int limit) throws DaoException;
}
