package com.tti.accscms.dao.movement;

import java.util.List;

import com.tti.accscms.domain.movement.ShipmentSearchCondition1;
import com.tti.accscms.domain.movement.ShipmentSearchCondition1Example;

import com.tti.accscms.dao.DaoException;

/**
 * This interface was generated by Generator.
 * This interface corresponds to the database table shipment_search_condition_1
 */
public interface ShipmentSearchCondition1Dao {
    
    public int count() throws DaoException;

    public int deleteById(Integer id) throws DaoException;

    public int insert(ShipmentSearchCondition1 shipmentSearchCondition1) throws DaoException;

    public ShipmentSearchCondition1 findById(Integer id) throws DaoException;
	
	public int update(ShipmentSearchCondition1 shipmentSearchCondition1) throws DaoException;
	
	public int countByShipmentSearchCondition1Example(ShipmentSearchCondition1Example shipmentSearchCondition1Example) throws DaoException;
	
	public ShipmentSearchCondition1 findByShipmentSearchCondition1Example(ShipmentSearchCondition1Example shipmentSearchCondition1Example) throws DaoException;
	
    public List<ShipmentSearchCondition1> findAllByShipmentSearchCondition1Example(ShipmentSearchCondition1Example shipmentSearchCondition1Example) throws DaoException;
    
    public List<ShipmentSearchCondition1> findAllByShipmentSearchCondition1Example(ShipmentSearchCondition1Example shipmentSearchCondition1Example, int limit) throws DaoException;
    
    public List<ShipmentSearchCondition1> findAllByShipmentSearchCondition1Example(ShipmentSearchCondition1Example shipmentSearchCondition1Example, int offset, int limit) throws DaoException;
}
